### ISSUE TITLE
 Viomi V2 Pro support

### ISSUE THREAD

**Issue by ShayShahar** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#199]
Can you please add support for Viomi v2 pro?

**Comment by afharo** [comment]
Hi @ShayShahar, there is an ongoing attempt to add support to `viomi` products. Apparently, they have a different set of commands.
Would you mind providing the full coded model so we can map it to the right set of commands in the `homebridge-xiaomi-roborock-vacuum@next` version?

It should look something like `viomi.vacuum.v2` or similar.

To retrieve it, try to run this module and provide the logs you get, please.

**Comment by afharo** [comment]
Sorry I closed this... It was because I merged the changes that were meant to fix the issue 😅 
Please, feel free to reopen it if the latest release is not working for your model.

**Comment by ojoaosemtil** [comment]
Ok, everything is working fine, except de motion sensor and battery level..hope you can find a way to fix it, but thank u very very much for all this!!

**Comment by Johannmann** [comment]
`[2020-5-25 0:04:55] [Xiaomi Viomi V2 Pro] ERR getCleaning | Failed getting the cleaning status. TypeError: Cannot read property 'property' of null
    at XiaomiRoborockVacuum.get isCleaning [as isCleaning] (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:795:32)
    at XiaomiRoborockVacuum.getCleaning (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:801:31)
    at /usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:149:49
    at module.exports (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:26)
    at On.<anonymous> (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:149:26)
    at On.emit (events.js:223:5)
    at On.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at On.Characteristic._this.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:462:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1215:22
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1143:10)
    at HAPServer.emit (events.js:223:5)
    at HAPServer.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:756:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:280:24)
    at IncomingMessage.emit (events.js:223:5)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[2020-5-25 0:04:55] [Xiaomi Viomi V2 Pro] ERR getWaterSpeed | No vacuum cleaner is discovered yet.
[2020-5-25 0:04:55] [Xiaomi Viomi V2 Pro] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
[2020-5-25 0:05:04] [Xiaomi Viomi V2 Pro] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, token might be wrong`

**Comment by afharo** [comment]
Hi @Johannmann that error looks like a connection error: `Could not connect to device, token might be wrong`.

Can you make sure after 2 minutes it successfully connected? Or can you revisit the token or IP are correct?

**Comment by Johannmann** [comment]
Hey, will do. Thanks!

I found the coded model next to the token. It's the `viomi.vacuum.v6`. I bought it as Viomi V2 Pro

**Comment by Johannmann** [comment]
Obviously, it was the token. Didn't decrypt it..
I can confirm viomi.vacuum.v6 works👍

**Comment by afharo** [comment]
Awesome! Thank you for confirming!
