### ISSUE TITLE
Crashed home bridge trying to update

### ISSUE THREAD

**Issue by asbesto01** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#213]
Hello everybody, this morning trying to update to latest version of the plugin, home bridge said:

npm WARN homebridge-xiaomi-roborock-vacuum@0.11.1 requires a peer of homebridge@
>=0.4.45 but none is installed. You must install peer dependencies yourself.

now I cannot start anymore the homebridge with following error:

Error: The requested accessory 'XiaomiRoborockVacuum' was not registered by any plugin.
    at PluginManager.getPluginForAccessory (C:\Users\PersonalComputerHP\AppData\Roaming\npm\node_modules\homebridge\lib\pluginManager.js:128:27)
    at C:\Users\PersonalComputerHP\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:237:45
    at Array.forEach (<anonymous>:null:null)
    at Server._loadAccessories (C:\Users\PersonalComputerHP\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:222:33)
    at Server.start (C:\Users\PersonalComputerHP\AppData\Roaming\npm\node_modules\homebridge\lib\server.js:76:18)
    at cli (C:\Users\PersonalComputerHP\AppData\Roaming\npm\node_modules\homebridge\lib\cli.js:88:12)
    at Object.<anonymous> (C:\Users\PersonalComputerHP\AppData\Roaming\npm\node_modules\homebridge\bin\homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

any ideas?

**Comment by asbesto01** [comment]
Solved rolling back to 0.8.0, but cannot update otherwise I have again the same issue!

**Comment by barneyonline** [comment]
Got the same error, "npm WARN homebridge-xiaomi-roborock-vacuum@0.11.1 requires a peer of homebridge@=0.4.45 but none is installed. You must install peer dependencies yourself."

Rolled back to 0.8.0

**Comment by iMike96** [comment]
I have the same issue unfortunately on rPi 4 running latest homebridge. I'll downgrade to previous version.

**Comment by iMike96** [comment]
After a reboot and retrying the installation through Homebridge terminal, I ran this command and now it seems to work with 0.11.1:

sudo -E -n npm -g install homebridge-xiaomi-roborock-vacuum@latest --force

Hope it will help you guys.

**Comment by barneyonline** [comment]
Thanks @iMike96 - tried that and still got the same error (along with a bunch of others)

**Comment by asbesto01** [comment]
> After a reboot and retrying the installation through Homebridge terminal, I ran this command and now it seems to work with 0.11.1:
> 
> 
> 
> sudo -E -n npm -g install homebridge-xiaomi-roborock-vacuum@latest --force
> 
> 
> 
> Hope it will help you guys.

Tried and solved thanks

**Comment by afharo** [comment]
Thank you for letting us know... I've removed `homebridge` from the `peerDependencies` list:
`homebridge-xiaomi-roborock-vacuum@0.11.2`
