### ISSUE TITLE
ERR setCleaning 

### ISSUE THREAD

**Issue by Skull09rus** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#215]
Hello everyone! Before installing v0.11.1, everything worked well, after updating, clicking on the cleaning in the room in the log gives an error and does not work
[5/24/2020, 19:04:37] [Xiaomi Mi Robot Vaccum 1S] INF getPauseState | roborock.vacuum.m1s | Pause possible is false
[5/24/2020, 19:04:37] [Xiaomi Mi Robot Vaccum 1S] INF getBatteryLow | roborock.vacuum.m1s | Batterylevel is 91%
[5/24/2020, 19:04:42] [Xiaomi Mi Robot Vaccum 1S] ACT setCleaning | roborock.vacuum.m1s | Start cleaning Room ID 2, not charging.
[5/24/2020, 19:04:43] [Xiaomi Mi Robot Vaccum 1S] ERR setCleaning | roborock.vacuum.m1s | Failed to set cleaning to true Error: Could not complete call to device
    at checkResult (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/checkResult.js:9:11)
    at XiaomiRoborockVacuum.setCleaningRoom (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:851:9)
    at module.exports (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:20)

**Comment by agafirss** [comment]
The same problem.
problem if I run only in 1 room

> [5/24/2020, 9:04:34 PM] [Mi Robot 1S] ERR setCleaning | roborock.vacuum.m1s | Failed to set cleaning to true Error: Could not complete call to device
>     at checkResult (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/checkResult.js:9:11)
>     at XiaomiRoborockVacuum.setCleaningRoom (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:851:9)
>     at module.exports (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:20)

**Comment by afharo** [comment]
Hmm! Interesting! I did change the way room cleaning worked for that model because of #141 

So the same model behaves differently :/

**Comment by afharo** [comment]
`homebridge-xiaomi-roborock-vacuum@0.11.3` should fix the issue
