### ISSUE TITLE
Xiaomi Vacuum cleaner 1S Room Cleaning issue

### ISSUE THREAD

**Issue by utester123123bb** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#224]
Hi. I have Xiaomi Vacuum cleaner 1S. All features works fine except Room Cleaning. I tried to run SemiAutomatic mode with Autoroom but rooms never shown in the Apple Home app. Wnen I copy room ID from the console logs and added ID's to config manually the rooms starts shown in Apple Home but nothing happen when I tap on it. In Console I got an error "ERR setCleaning | roborock.vacuum.m1s | Failed to set cleaning to true Error: Could not complete call to device
    at checkResult (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/checkResult.js:9:11)
    at XiaomiRoborockVacuum.setCleaningRoom (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:851:9)
    at module.exports (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:20)
"
All other features like Dock status, On/Off works fine. Please suggest.

**Comment by utester123123bb** [comment]
> Hi. I have Xiaomi Vacuum cleaner 1S. All features works fine except Room Cleaning. I tried to run SemiAutomatic mode with Autoroom but rooms never shown in the Apple Home app. Wnen I copy room ID from the console logs and added ID's to config manually the rooms starts shown in Apple Home but nothing happen when I tap on it. In Console I got an error "ERR setCleaning | roborock.vacuum.m1s | Failed to set cleaning to true Error: Could not complete call to device
> at checkResult (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/checkResult.js:9:11)
> at XiaomiRoborockVacuum.setCleaningRoom (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:851:9)
> at module.exports (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:20)
> "
> All other features like Dock status, On/Off works fine. Please suggest.

Fixed, Please discard.
