### ISSUE TITLE
Failing to connect due to invalid token

### ISSUE THREAD

**Issue by beckern** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#229]
Guten Morgen,

nach der Installation des Plugins bekomme ich folgenden Fehler:

ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, token might be wrong
ERR getCleaning | Failed getting the cleaning status. TypeError: Cannot read property 'property' of null
    at XiaomiRoborockVacuum.get isCleaning [as isCleaning] (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:800:32)
    at XiaomiRoborockVacuum.getCleaning (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:806:31)
    at callbackify (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:153:49)
    at module.exports (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:26)
    at On.services.fan.getCharacteristic.on (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:153:26)
    at On.emit (events.js:198:13)
    at On.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at On.Characteristic._this.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:462:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1215:22
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1143:10)
    at HAPServer.emit (events.js:198:13)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:756:12)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:280:24)
    at IncomingMessage.emit (events.js:198:13)
[9.6.2020, 10:42:14] [rockrobo] ERR getPauseState | No vacuum cleaner is discovered yet.

Angesteuert werden soll ein Roborock S6. Den Token habe ich über meinen Raspberry mit wicd-curses und anschließend miio discover ausgelesen.

Gibt es verschiedene Token?

Kann mir jemand helfen!?

Danke!

**Comment by afharo** [comment]
Hi @beckern,

The main error is this one:
```
ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, token might be wrong
```
The rest are just related to the fact that the module failed to connect in first place. 

Did you try the methods explained in https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#xiaomi-token to extract the token?

A couple of things to take into consideration: if you reset the vacuum in any form: set the wifi again, link it to a new app (Roborock App vs. Xiaomi MiHome app #104) or even linked to both apps, you switch from one to another, the tokens are reissued and any previous one is revoked.

**Comment by beckern** [comment]
Hello,
yes, I extract the token with Varinate 3 of https://forum.smartapfel.de/forum/thread/370-xiaomi-token-auslesen/
and write down into the config.json

Is it possible the I get a wrong token?

**Comment by beckern** [comment]
I have solved the problem.

**Comment by beckern** [comment]
The Variant 3 is not to yous, because the roborock gets a new token when connected with the correct wlan.

**Comment by afharo** [comment]
Oh! Makes sense! Thank you for confirming! Can we close this issue then?
