### ISSUE TITLE
viomi.vacuum.v7 is getting ERR getRoomMap | Failed getting the Room Map

### ISSUE THREAD

**Issue by timothy-morph** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#231]
Hi there, I have the "viomi.vacuum.v7" model, and thanks for the cool plugin, I've got most of it working in homebridge.
But I couldn't get the room working.
I've tried both the semi automatic way and the autoroom way, but none of them work.
Is there any thing I should try?
Big Thanks!

Here's the result after I tried:
**semi automatic:**
> all the rooms showed up in the accessories, and the robot will start but end immediately and went back to the dock without doing any cleaning.

**Automatic:** here's the error I've got from the log:
`[6/10/2020, 4:20:00 PM] [Cleaning Bot] ERR getRoomMap | Failed getting the Room Map. Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/Users/timothy/.npm-global/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/network.js:519:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  code: 'timeout'
}
[6/10/2020, 4:20:00 PM] [Cleaning Bot] ERR connect | miio.device, next try in 2 minutes | Error: Call to device timed out`

**Comment by Bene2103** [comment]
You can easily get the room numbers via python-miio. 

miiocli viomivacuum --ip yourrobotiphere --token yourtokenhere raw_command set_mode_withroom 0,1,1,13 

The last number is the room number which your robot generates itself. Just change the numbers an see in which room the robot goes. Then you can define your rooms in your config.json

 "rooms": [
    {
      "id": 16,
      "name": "Livingroom"
    },
    {
      "id": 17,
      "name": "Kitchen"
    }
  ],

Hope this helps :-)

**Comment by Bene2103** [comment]
Yes, I’ve tried every number until I got all the rooms. 

Haven’t controlled the mopping feature through Homebridge yet, what happens if you set the Y-pattern in the app and start a cleaning via Homebridge? 

Maybe have a look over here, there’s a list with all compatible commands. 

https://github.com/rytilahti/python-miio/issues/550#issuecomment-552780952

**Comment by timothy-morph** [comment]
I see :D, thanks~~ I got some rooms now and will continue to get all of it~~

About the moping pattern, I've tried setting the Y-pattern in the app but it keep doing the S-pattern if I start the cleaning from homebridge (and miiocli), I'll look into the link you posted and see what I can find :D!! 
Thanks a lot for helping out!

**Comment by afharo** [comment]
Oh! I didn't know the Y vs. S pattern was a thing! Really intrigued with that. Please, let us know if you find out anything with the raw commands via the python library and I'll be happy to add it to the module (or if you are willing to create a Pull Request yourself... 😉 )

**Comment by timothy-morph** [comment]
Thanks :) so far I couldn't find anything in miio or python-miio about mopping patterns but I'll keep digging. 👍 I'll post it here if I find anything :)

**Comment by timothy-morph** [comment]
Hi, I opened an issue on python-miio and got an answer 😃~
There seems to be a command "set_moproute [0/1]" for the pattern.
Too bad I'm not skilled enough to know what to do with it. 🤔~ 
Here's where I got it from. [https://github.com/rytilahti/python-miio/issues/725](url)
Is there anything I can start with? or how?

**Comment by afharo** [comment]
This is awesome! Thank you!

I'll try to add it as a parameter in the `config.json` file. 

Do you know if this is something we need to call every time we start a cleaning session? Before or after the _start_ command? Or is it a parameter called just once?

I'm still puzzled: because it looks like you have it set to the Y-pattern already in your app, but the cleaning sessions still start in S-pattern mode, so I'm wondering if we are overwriting it when triggering the cleaning session.

Can you try something locally?
If you change this line in your local installation:
https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/blob/master/miio/lib/devices/viomivacuum.js#L169
to...
```
    return this.call("set_mode_withroom", [1, 1, 0], {
```

(don't forget to restart `homebridge` after your changes). Will it work?

**Comment by timothy-morph** [comment]
Hi :D,
Looks like they are just going to add this command to the python-miio, check this out:
[https://github.com/rytilahti/python-miio/issues/725#issuecomment-643823146](url)
![image](https://user-images.githubusercontent.com/50393226/84643739-d5e3f980-af30-11ea-8a7c-63f804554e2b.png)

So I think we cannot use it yet?

and I'll try what you said tonight and see what happens :) Thanks!!

**Comment by afharo** [comment]
We don't rely on the python-miio library for this module. But they have somehow access to _decode_ the firmwares of the Xiaomi Vaccuums to find out which commands to run. That's why we use it in this module for reference :)
Once they find the command, we can/have to implement it ourselves in our JS module 😉

**Comment by timothy-morph** [comment]
oh I see :) ~ Thanks :D

And I tried to change the code in viomivacuum.js#L169 but with no luck
It still stick to the S-pattern when I send it out for room cleaning from homebridge.
Anything I can also tryout?

**Comment by afharo** [comment]
Oh! for room cleaning you have to change it in line 153 :)
https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/blob/master/miio/lib/devices/viomivacuum.js#L153

Change the initial 0 to 1 and see if it does the Y-pattern :)

**Comment by timothy-morph** [comment]
Great news! 😃
Changing line 153 made it do the Y-pattern now!
Thank you sooooo much~

**Comment by afharo** [comment]
Brilliant! Thank you for confirming! 
I'll add a parameter in the config.json file so we can define it for these Viomi models. 

If that's OK, I'll update the title of this issue to remind us what we've achieved here :)

**Comment by timothy-morph** [comment]
No problem :) Thank you!!

**Comment by Michaal465** [comment]
Which Viomi model do you have? It works with Viomi V3?

**Comment by timothy-morph** [comment]
It was viomi.vacuum.v7, but I had replaced it with Roborock T7.
