### ISSUE TITLE
Mi Robot P

### ISSUE THREAD

**Issue by sebastianpisula** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#234]
Hi, 

I try to add to Homebridge my vacuum but I have errors in logs:

> [6/19/2020, 10:30:48] [Xiaomi Mi Robot Vaccum 1st Generation] ERR getCleaning | Failed getting the cleaning status. TypeError: Cannot read property 'property' of null
>     at XiaomiRoborockVacuum.get isCleaning [as isCleaning] (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:800:32)
>     at XiaomiRoborockVacuum.getCleaning (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:806:31)
>     at /usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:153:49
>     at module.exports (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:26)
>     at On.<anonymous> (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:153:26)
>     at On.emit (events.js:310:20)
>     at On.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
>     at On.Characteristic._this.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:462:12)
>     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1215:22
>     at Array.forEach (<anonymous>)
> [6/19/2020, 10:30:48] [Xiaomi Mi Robot Vaccum 1st Generation] ERR getPauseState | No vacuum cleaner is discovered yet.
> [6/19/2020, 10:30:48] [Xiaomi Mi Robot Vaccum 1st Generation] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
> [6/19/2020, 10:30:52] [Xiaomi Mi Robot Vaccum 1st Generation] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, token might be wrong
> [6/19/2020, 10:30:55] [Xiaomi Mi Robot Vaccum 1st Generation] ERR getCleaning | Failed getting the cleaning status. TypeError: Cannot read property 'property' of null
>     at XiaomiRoborockVacuum.get isCleaning [as isCleaning] (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:800:32)
>     at XiaomiRoborockVacuum.getCleaning (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:806:31)
>     at /usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:153:49
>     at module.exports (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:26)
>     at On.<anonymous> (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:153:26)
>     at On.emit (events.js:310:20)
>     at On.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
>     at On.Characteristic._this.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:462:12)
>     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1215:22
>     at Array.forEach (<anonymous>)
> [6/19/2020, 10:30:55] [Xiaomi Mi Robot Vaccum 1st Generation] ERR getPauseState | No vacuum cleaner is discovered yet.
> [6/19/2020, 10:30:55] [Xiaomi Mi Robot Vaccum 1st Generation] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
> [6/19/2020, 10:31:05] [Xiaomi Mi Robot Vaccum 1st Generation] ERR getCleaning | Failed getting the cleaning status. TypeError: Cannot read property 'property' of null
>     at XiaomiRoborockVacuum.get isCleaning [as isCleaning] (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:800:32)
>     at XiaomiRoborockVacuum.getCleaning (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:806:31)
>     at /usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:153:49
>     at module.exports (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:26)
>     at On.<anonymous> (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:153:26)
>     at On.emit (events.js:310:20)
>     at On.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
>     at On.Characteristic._this.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:462:12)
>     at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1215:22
>     at Array.forEach (<anonymous>)
> [6/19/2020, 10:31:05] [Xiaomi Mi Robot Vaccum 1st Generation] ERR getPauseState | No vacuum cleaner is discovered yet.
> [6/19/2020, 10:31:05] [Xiaomi Mi Robot Vaccum 1st Generation] INF ensureDevice | undefined | The socket was destroyed or not initialised, initialising the device
> [6/19/2020, 10:31:07] [Xiaomi Mi Robot Vaccum 1st Generation] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, token might be wrong

**Comment by afharo** [comment]
This is the key message from the logs:

```
 [6/19/2020, 10:30:52] [Xiaomi Mi Robot Vaccum 1st Generation] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, token might be wrong
```

Can you double check the token is correct?

**Comment by ktsi** [comment]
Exact same issue here as well. Token is correct but i am getting the same error message. Can someone please help?

**Comment by afharo** [comment]
If you run the command: `miio-vacuum discover --token YOUR_TOKEN_HERE`, what do you get?

I get something like:

```
 INFO  Discovering devices. Press Ctrl+C to stop.

Device ID: 968xxxxx
Model info: roborock.vacuum.s5
Address: 192.168.xxx.xxx
Token: YOUR_TOKEN_HERE
Support: At least basic

```

**Comment by ktsi** [comment]
Hi! Thanks for getting back. I am currently on vacation. I will get back ASAP (could be another two weeks though).

**Comment by ktsi** [comment]
Hi. I tried again with version 0.13.4 and I still get the same error. I found the token via a JB android device (same way I found tokens for other Xiaomi devices) so i assume it is correct. This miio command you refer to, is that a python program?

**Comment by afharo** [comment]
> This miio command you refer to, is that a python program?

No, it's installed as part of this plugin ;)

https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/blob/b5a419037eeff417ad21e9a2feda969a7c2836d2/package.json#L33-L35

**Comment by ktsi** [comment]
How w do i run this? I will try that later on today.

**Comment by afharo** [comment]
Usually, simply by installing the npm library (in this case `npm -g install homebridge-xiaomi-roborock-vacuum`), it should automatically add it to your `/usr/local/bin` or similar paths. So it should be a command available for you out of box after installing this library.

**Comment by ktsi** [comment]
Just tried the miio command.
This is what i get.

![image](https://user-images.githubusercontent.com/3631010/90064958-2fc82c00-dcf4-11ea-9b8b-afce89ab2c89.jpeg)

**Comment by afharo** [comment]
hmmm, `Model info: Unknown`... that's intriguing... So this device is not returning his own model info in this simple request? 😮

**Comment by ktsi** [comment]
Bump. Any news?

**Comment by afharo** [comment]
Sorry, I didn't have the chance to work on this. Also, I don't own that device which will make it harder for me to know the specifics of that device. 

If you could check if [this other python project](https://github.com/rytilahti/python-miio) supports that model, I can try to migrate the commands. They are usually ahead of this module because they can somehow reverse engineer the firmware of each model.

**Comment by ktsi** [comment]
Hi. It seems that the miio project already supports this model number. Pasting the relevant text here: Xiaomi Mijia STYJ02YM (Viomi)

**Comment by afharo** [comment]
Happy days!! Then I'll be able to extract the commands from them. Thank you for sharing the news!

**Comment by ktsi** [comment]
Please let us know if you have some progress. 

Thanks a lot in advance.

**Comment by sebastianpisula** [comment]
Any updates?

**Comment by ktsi** [comment]
Hi. Bump!

**Comment by sebastianpisula** [comment]
Any updates? Or any info how can I add my device to homebridge? :)

> pi@homebridge:/var/lib/homebridge $ miio-vacuum discover
 INFO  Discovering devices. Press Ctrl+C to stop.
> 
> Device ID: 309270216
> Model info: Unknown
> Address: 192.168.0.14
> Token: ???
> Support: Unknown

**Comment by afharo** [comment]
There is a basic support for Viomi models. Can you try it out?
