### ISSUE TITLE
0.12.1 problem

### ISSUE THREAD

**Issue by adamrzanek** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#253]
Latest version (0.12.1) crashing homebridge. Had to revert to 0.12

**Comment by Skull09rus** [comment]
same thing 
[7/13/2020, 21:45:27] ReferenceError: callbackify is not defined
    at On.<anonymous> (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:983:26)
    at On.emit (events.js:315:20)
    at On.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at On.Characteristic._this.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:488:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1216:13
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1142:3)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:756:12)
[7/13/2020, 21:45:27] [Hue] heartbeat 191, drift 293
[7/13/2020, 21:45:27] Got SIGTERM, shutting down Homebridge...

**Comment by vek030** [comment]
The same for me, too. Had to revert to 0.12.0 and Homebridge works

**Comment by cgilis** [comment]
Anyone can tell me how to revert in a docker config ui x?

**Comment by snookerap** [comment]
The same for me, too.

**Comment by vtl3004** [comment]
Same too
`[2020-7-14 9:13:55] [Пылесос] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[2020-7-14 9:13:55] [Пылесос Комната] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[2020-7-14 9:13:55] [Пылесос Стол] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[2020-7-14 9:13:55] [Пылесос Прихожая] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[2020-7-14 9:13:55] [Пылесос Кухня] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[2020-7-14 9:13:55] [Пылесос Диван] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[2020-7-14 9:14:08] ReferenceError: callbackify is not defined
    at On.<anonymous> (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:1005:26)
    at On.emit (events.js:315:20)
    at On.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at On.Characteristic._this.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:462:12)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1215:22
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._this._handleGetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1143:10)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:756:12)`

**Comment by det-box** [comment]
Hi.
The same for me, too. Had to revert to 0.12.0 and Homebridge works

> same thing
> [7/13/2020, 21:45:27] ReferenceError: callbackify is not defined
> at On. (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:983:26)
> at On.emit (events.js:315:20)
> at On.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
> at On.Characteristic._this.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:488:12)
> at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1216:13
> at Array.forEach ()
> at Bridge.Accessory._this._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1142:3)
> at HAPServer.emit (events.js:315:20)
> at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
> at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:756:12)
> [7/13/2020, 21:45:27] [Hue] heartbeat 191, drift 293
> [7/13/2020, 21:45:27] Got SIGTERM, shutting down Homebridge...

**Comment by cgilis** [comment]
> Anyone can tell me how to revert in a docker config ui x?

Found it, rollback in Docker:
sudo npm install  --save homebridge-xiaomi-roborock-vacuum@0.12

**Comment by afharo** [comment]
Sorry! My bad! It should be fixed in 0.12.2
