### ISSUE TITLE
Error communicating with Robot Vacuum

### ISSUE THREAD

**Issue by gjanos89** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#281]
Hello,

I have an issue connecting to my new Mi Robot Vacuum-Mop device. 
Token and IP read is correct (I can clearly see in the log if I change the token and it is not correct).

Homebridge is running on a raspberry pi4 4gb since a week, so it is a new version running:
Hombridge Version v1.1.2
Node.js Version v12.18.3
Npm Version v6.14.8

After connecting and accessories appear they remain unresponsive.
Some data is retracted e.g. IP, model, Firmware version, other info is undefined or unknown. 

Here is my log content from the connection onwards:

[9/1/2020, 1:09:21 PM] [Monica] STA getDevice | Connected to: 192.168.89.34
[9/1/2020, 1:09:21 PM] [Monica] STA getDevice | Model: dreame.vacuum.mc1808
[9/1/2020, 1:09:21 PM] [Monica] STA getDevice | State: undefined
[9/1/2020, 1:09:21 PM] [Monica] STA getDevice | FanSpeed: undefined
[9/1/2020, 1:09:21 PM] [Monica] STA getDevice | BatteryLevel: undefined
[9/1/2020, 1:09:33 PM] [Monica] ERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
at Timeout.retry [as _onTimeout] (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/network.js:519:23)
at listOnTimeout (internal/timers.js:549:17)
at processTimers (internal/timers.js:492:7) {code: 'timeout'}
[9/1/2020, 1:09:33 PM] [Monica] STA getDevice | Serialnumber: Unknown
[9/1/2020, 1:09:33 PM] [Monica] INF getFirmware | dreame.vacuum.mc1808 | Firmwareversion is 3.5.8_1059
[9/1/2020, 1:09:33 PM] [Monica] STA getDevice | Firmwareversion: 3.5.8_1059
[9/1/2020, 1:09:45 PM] [Monica] ERR getState | {"code":"timeout"}
[9/1/2020, 1:10:27 PM] [Monica] ERR getState | {"code":"timeout"}
[9/1/2020, 1:10:57 PM] [Monica] ERR getState | {"code":"timeout"}

An example of me trying to send a find request to the robot Vacuum:

[9/1/2020, 3:16:28 PM] [Monica] ACT identify | dreame.vacuum.mc1808 | Find me - Hello!
[9/1/2020, 3:16:38 PM] [Monica] ERR identify | dreame.vacuum.mc1808 |  Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/network.js:519:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}
[9/1/2020, 3:16:39 PM] [Monica] INF getCleaning | dreame.vacuum.mc1808 | Cleaning is false
[9/1/2020, 3:16:39 PM] [Monica] INF getCareSensors | dreame.vacuum.mc1808 | Sensors dirtytime is undefined seconds / NaN%.
[9/1/2020, 3:16:39 PM] [Monica] INF getCareFilter | dreame.vacuum.mc1808 | Filter worktime is undefined seconds / NaN%.
[9/1/2020, 3:16:39 PM] [Monica] INF getCareSideBrush | dreame.vacuum.mc1808 | Sidebrush worktime is undefined seconds / NaN%.

**Comment by afharo** [comment]
Hi @gjanos89, I'm afraid that model is not supported yet.

It has an entirely new set of commands different to the rest of the Xiaomi models. There is this issue to track the process https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/150.

If you don't mind, I'll close this issue in favour to the other one.

**Comment by gjanos89** [comment]
hello @afharo,

Sorry did not realize that the 1C model is the same as mine, now looking into their logs I see the same model dreame.vacuum.mc1808 identified by the plugin. 

Of course I don't mind the closing, I am following now the #150 . 
If you need any help or you have description on how to identify the commands to support you!
