### ISSUE TITLE
Autoroom feature issue

### ISSUE THREAD

**Issue by davidszewczyk** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#283]
Hi, 

I would like to use autoroom feature for my Xiaomi Vacuum Mop Pro. Plugin is working with simple commends as start, stop, return to the dock but when I try to use autoroom feature I got this:

[9/2/2020, 4:55:05 PM] [Vacuum] ERR getRoomMap | Failed getting the Room Map. Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/network.js:519:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}
[9/2/2020, 4:55:05 PM] [Vacuum] ERR connect | miio.device, next try in 2 minutes | Error: Call to device timed out

I have named all my rooms in Xiaomi App. Any idea what's still is not right?

Thanks!

**Comment by afharo** [comment]
Hi @davidszewczyk, thank you for opening this issue. Does your model support naming the rooms in the Xiaomi Mi Home app? If the answer is no, you should follow the steps detailed in the semiautomatic process.

For more information on both type of models (those with naming option and those without it), you can follow the conversation in https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/277

**Comment by davidszewczyk** [comment]
Hi,

Yes, of course. My model is supporting naming rooms. I believe I have the same problem as user below:

https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/221

And I'm using the same model - viomi.vacuum.v8 (Mi Robot Vacuum Mop Pro). Is there some work around solution for this?

**Comment by afharo** [comment]
Oh! Viomi models have a fully different set of commands. I got this plugin to work on the basic modes, but autoroom is still in the pending list: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/216

I think you can try finding the room IDs by hand for now (like the other user mentioned in https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/221#issuecomment-635605074). Sorry there's no support for it yet 🙁

**Comment by davidszewczyk** [comment]
No worries. I took your advice and play around manually and I managed to find IDs of all my rooms except bedroom. I played around with ID between 10 and 26. This is how my list is looking right now:

`"rooms": [
                {
                    "id": 11,
                    "name": "Workshop"
                },
                {
                    "id": 12,
                    "name": "Livingroom"
                },
                {
                    "id": 13,
                    "name": "Kitchen"
                },
                {
                    "id": 14,
                    "name": "Bathroom"
                },
                {
                    "id": 16,
                    "name": "Corridor"
                },
                {
                    "id": ?,
                    "name": "Bedroom"
                }
            ]
‘
I tried to find Bedroom between IDs 17-26 without luck. Do you know by any chance what could be the reason of that?

**Comment by afharo** [comment]
I'm happy that it worked for you. 

Re the Bedroom, the IDs are assigned by the vacuum, so I can't really tell, only guess.

Silly question: have you tried with 15? It looks like there is a gap between the bathroom and the corridor 🙂 

Also, it has happened to me earlier: some times, even via the official app, the vacuum can't reach some rooms when the previous cleanup had any issue (i.e.: the door was closed so it couldn't reach that room that day). Maybe that could be messing up with your discovery?

**Comment by takenek** [comment]
Hello,
Problem still exist? i got same problem i use newlatest version of Homebridge and plugin.

[14.01.2022, 10:32:49] [Mi Robot Vacuum-Mop P] INF getFirmware | viomi.vacuum.v8 | Firmwareversion is 3.5.3_0017
[14.01.2022, 10:33:14] [Mi Robot Vacuum-Mop P] STA getDevice | Connected to: 192.168.1.123
[14.01.2022, 10:33:14] [Mi Robot Vacuum-Mop P] STA getDevice | Model: viomi.vacuum.v8
[14.01.2022, 10:33:14] [Mi Robot Vacuum-Mop P] STA getDevice | State: charging
[14.01.2022, 10:33:14] [Mi Robot Vacuum-Mop P] STA getDevice | FanSpeed: 3
[14.01.2022, 10:33:14] [Mi Robot Vacuum-Mop P] STA getDevice | BatteryLevel: 100
[14.01.2022, 10:33:24] [Mi Robot Vacuum-Mop P] ERR getRoomMap | Failed getting the Room Map. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at XiaomiRoborockVacuum.getRoomMap (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:1089:19)
    at XiaomiRoborockVacuum.initializeDevice (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:685:11)
    at XiaomiRoborockVacuum.connect (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:770:7) {
  code: 'timeout'
}
[14.01.2022, 10:33:24] [Mi Robot Vacuum-Mop P] ERR connect | miio.device, next try in 2 minutes | Error: Call to device timed out

Best Regards
TaKeN

**Comment by adamxfort** [comment]
Hey, you can youse room cleaning, you just have to get the rooms IDs using python-miio
I had issues installing it on windows, but it works through WSL. 
In the MiHome app create a new schedule at 00:00 with all but one room and another schedule with only the remaining room.

**Comment by afharo** [comment]
Hi! I think [v0.28.0](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.28.0) should fix this issue. I don't have that model. Would you mind testing it out?

**Comment by adamxfort** [comment]
Hey,I've tried to enable the autoroom feature on 0.28 with my xiaomi robot vacuum mop pro but I got the same issue with timeout following by a crash of the plugin
