### ISSUE TITLE
Room Cleaning starts Bot and Stops it immediately after undocking

### ISSUE THREAD

**Issue by edelmaca** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#295]
i just installed the plugin for my Roborock S5 Max and got it set up. I extracted the IDs of the Room. Everything without a problem.
The first run through shortcuts with HomeKit and Buttons went perfect but after testing the Room switches it got interesting.
After starting a Room Cleaning via the HomeKit app, the Bot confirmed this with the usual words ("Zimmerreinigung gestartet"-"Room Cleaning Started").
It starts driving backwards, out of the Dock, and stops to turn around...everything fine so far. But the it is not turning around. It is telling me it has endet the Room cleaning with the usual phrase ("Zimmerreinigung beendet"-"Room Cleaning done") and starts driving directly back into the Dock. 
Is someone having the same Issue? What could possibly be the problem, since the normal whole apartment cleaning is working fine?!

Heres the Log from start till dock:
[10/7/2020, 15:20:27] [Roborock S5 Max] ACT setCleaning | roborock.vacuum.s5e | Start cleaning Room ID 4, not charging.
[10/7/2020, 15:20:28] [Roborock S5 Max] INF changedPause | roborock.vacuum.s5e | Paused not possible, no cleaning
[10/7/2020, 15:20:28] [Roborock S5 Max] MON changedCharging | roborock.vacuum.s5e | ChargingState is now false
[10/7/2020, 15:20:28] [Roborock S5 Max] INF changedCharging | roborock.vacuum.s5e | Charging is cancelled
[10/7/2020, 15:20:28] [Roborock S5 Max] INF changedCharging | roborock.vacuum.s5e | Robot not anymore in dock.
[10/7/2020, 15:20:28] [Roborock S5 Max] INF changedCleaning | roborock.vacuum.s5e | Cleaning is ON.
[10/7/2020, 15:20:28] [Roborock S5 Max] INF changedPause | roborock.vacuum.s5e | Paused possible
[10/7/2020, 15:20:31] [Roborock S5 Max] INF getDocked | roborock.vacuum.s5e | Robot Docked is false (Status is room-cleaning)
[10/7/2020, 15:20:31] [Roborock S5 Max] INF getBattery | roborock.vacuum.s5e | Batterylevel is 71%
[10/7/2020, 15:20:41] [Roborock S5 Max] INF getDocked | roborock.vacuum.s5e | Robot Docked is false (Status is room-cleaning)
[10/7/2020, 15:20:41] [Roborock S5 Max] INF getBattery | roborock.vacuum.s5e | Batterylevel is 71%
[10/7/2020, 15:20:51] [Roborock S5 Max] INF getDocked | roborock.vacuum.s5e | Robot Docked is false (Status is room-cleaning)
[10/7/2020, 15:20:51] [Roborock S5 Max] INF getBattery | roborock.vacuum.s5e | Batterylevel is 71%
[10/7/2020, 15:21:01] [Roborock S5 Max] INF getDocked | roborock.vacuum.s5e | Robot Docked is false (Status is room-cleaning)
[10/7/2020, 15:21:01] [Roborock S5 Max] INF getBattery | roborock.vacuum.s5e | Batterylevel is 71%
[10/7/2020, 15:21:02] [Roborock S5 Max] MON changedCharging | roborock.vacuum.s5e | ChargingState is now true
[10/7/2020, 15:21:02] [Roborock S5 Max] INF changedCharging | roborock.vacuum.s5e | Charging is active
[10/7/2020, 15:21:02] [Roborock S5 Max] INF changedCharging | roborock.vacuum.s5e | Robot was docked.
[10/7/2020, 15:21:02] [Roborock S5 Max] INF changedCleaning | roborock.vacuum.s5e | Cleaning is OFF.
[10/7/2020, 15:21:02] [Roborock S5 Max] INF changedPause | roborock.vacuum.s5e | Paused not possible, no cleaning
[10/7/2020, 15:21:02] [Roborock S5 Max] INF changedPause | roborock.vacuum.s5e | Paused not possible, no cleaning

My config of this Plugin:
{
            "name": "Roborock S5 Max",
            "ip": "192.168.0.58",
            "token": "mytoken",
            "waterBox": false,
            "pause": true,
            "pauseWord": "Pause",
            "findMe": false,
            "findMeWord": "where are you",
            "dock": true,
            "delay": false,
            "cleanword": "Sauge",
            "autoroom": false,
            "rooms": [
                {
                    "name": "Wohnzimmer",
                    "id": 0
                },{
                    "name": "Küche",
                    "id": 1
                },{
                    "name": "Bad",
                    "id": 2
                },{
                    "name": "Flur",
                    "id": 3
                },{
                    "name": "Schlafzimmer",
                    "id": 4
                }
            ],
            "accessory": "XiaomiRoborockVacuum"
        }

I appreciate any help or tip to the solution.

**Comment by afharo** [comment]
Hmm, do you get the same behaviour when you try to clean the same room via the Xiaomi app?

AFAIK, the vacuum sometimes behaves like that when it doesn't know how to reach to the room. If a previous cleaning has ocurred, and there was a closed door (or similar) that the robot understood as a no-go.

Can you try a full cleaning and, once the map has been redrawn, try with the room individual cleanings?

**Comment by edelmaca** [comment]
This is what I did. I completed a normal cleaning round without any problems. After confirming everything went fine, I started a room cleaning. It is acting like this for every room.

**Comment by edelmaca** [comment]
New insight. 
If I first press the pause switch in HomeKit, shortly after this the room switch for the room I want to be cleaned, the cleaning is going through perfectly fine.
But why is that? That can't be normal, to always have to switch on pause, then hit the room switch. Like this it's nearly impossible to start the cleaning with Siri.

**Comment by cde010** [comment]
I am having this same issue.  When a room is selected, the robot leaves the dock and immediately returns.

**Comment by DocUltra** [comment]
I have the same behavior, when a room is selected?

**Comment by koraykupe** [comment]
Same error on S5 Max.

**Comment by GunnarBaldursson** [comment]
Same Error here on Viomi V3

**Comment by BjornB2** [comment]
Also the same behavior here. S5. The voice of the S5 is telling me something but it is impossible to understand with the noise of the vacuum on.

**Comment by BjornB2** [comment]
I do get these lines at startup:

`[11/6/2020, 8:27:43 PM] [Stoffie] Initializing XiaomiRoborockVacuum accessory...
[11/6/2020, 8:27:43 PM] [Stoffie] INF createRoom | undefined | Room In de keuken (0) undefined
[11/6/2020, 8:27:43 PM] [Stoffie] INF createRoom | undefined | Room Onder de tafel (1) undefined
[11/6/2020, 8:27:43 PM] [Stoffie] INF createRoom | undefined | Room Bij de bank (2) undefined
HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
Setup Payload:
X-HM://0023ISYWYA990`

I don't know what it means but a warning near an accessory that is not working could be a clue 🕵🏻‍♂️

**Comment by BjornB2** [comment]
Ok I found out it says "Room cleaning incomplete, could not find the specified room" and then "going back to the dock".

**Comment by GunnarBaldursson** [comment]
Mine says "Cleanup has ended, returning to the dock to charge"

**Comment by BjornB2** [comment]
Ah I think I am getting somewhere. If you turn autoroom on, and then in the config make sure that it shows like this:

autoroom: [room1, room2, room3] and then restart homebridge, it shows the actual room ID's during boot and it creates the rooms. 

Other considerations: It didn't work with a repeating timer. I had to make a timer set at 00:00 and run once (and deactivate it) and in the timer select the rooms in the same order you use in the autoroom list.

**Comment by GunnarBaldursson** [comment]
0/11/2020, 12:17:12 [Viomi V3] ACT setCleaning | viomi.vacuum.v13 | Start cleaning Room ID 2, not charging. undefined
10/11/2020, 12:17:14 [Viomi V3] ERR setCleaning | viomi.vacuum.v13 | Failed to set cleaning to true Error: Could not complete call to device
    at checkResult (/home/hoobs/.hoobs/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/checkResult.js:9:11)
    at async XiaomiRoborockVacuum.setCleaningRoom (/home/hoobs/.hoobs/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:917:9)
    at async module.exports (/home/hoobs/.hoobs/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:20)

This is what my log says when I try to send the robot in a specific room

**Comment by afharo** [comment]
@GunnarBaldursson, based on @BjornB2's comment. It looks to me like fixing the room config worked for him.

Can you confirm your Room IDs are correct?

**Comment by GunnarBaldursson** [comment]
How can I confirm that. I got the room ID by the same whay bjorn is describing.

**Comment by GunnarBaldursson** [comment]
this is my room config 

{
        "id": 0,
        "name": "Living room"
    },
    {
        "id": 1,
        "name": "Entrance"
    },
    {
        "id": 2,
        "name": "Kitchen"
    },
    {
        "id": 3,
        "name": "Master bedroom"
    },
    {
        "id": 4,
        "name": "Bedroom"
    }

these are the ID's I got by creating a timer in the Xiaomi home app and restarting homebridge

**Comment by BjornB2** [comment]
I think I would retry the discovery of the room ID's. If you look at mine they aren't even sequential and don't start at 0.

**Comment by GunnarBaldursson** [comment]
I will try that when I have time. Did you not name your rooms in advance Bjorn?

**Comment by BjornB2** [comment]
I did but it doesn't matter. I used the semi automatic method just to discover the ID's and then entered them manually.
On 10 Nov 2020, 16:17 +0100, GunnarBaldursson <notifications@github.com>, wrote:

I will try that when I have time. Did you not name your rooms in advance Bjorn?

**Comment by GunnarBaldursson** [comment]
These are the ID's I get when go by these instructions.

@afharo Thank you mate! It worked for me.

@PrimaryInc Here is my manual :).
My roborock: S5 with Firmware 3.5.7_002008

Open Homebridge web-interface and log in.
Go to Plugins tab and click on Settings for "Homebridge Xiaomi Roborock Vacuum".
Scroll down, activate the checkbox for "Automatic Room Detection".
Make sure "Rooms" is empty and save.
Go to Configuration tab and search under "accessories" the keyword "autoroom".
It should be "autoroom": true,.
Change it to "autoroom": ["Room1", "Room2", "RoomN"], and save it.
Go to Xiaomi Home App and click on your roborock.
Click on the three dots in the uppe right to open the roborock menu and click on "Timer".
Create a new timer with "Start: 00:00".
Select "Select zones" and then select all rooms in the exact same order, you typed in step 7.
Save the timer and disable it.
Go back to Homebridge web-interface and restart Homebridge.
After the restart you will see something like that in the logfiles of Homebridge:
[Roborock] INF getRoomList | roborock.vacuum.s5 | Created "rooms": [{"id":16,"name":"Room1"},{"id":18,"name":"Room2"},{"id":17,"name":"RoomN"}]
Save those IDs.
Go back to the Plugin configuration. "Automatic Room Detection" should now be disabled.
Now enter all your rooms with the corresponding ID under "Rooms" and save.
Restart Homebridge.
Now all rooms should appear in the Home App.
You can delete the timer in the Xiaomi Home App.
PS: If a room doesn't work, make sure the IDs are correct. E.g. you selected the rooms in the wrong order in the Xiaomi Home App.

I hope it will help :).


11/11/2020, 15:31:05 [Viomi V3] Initializing XiaomiRoborockVacuum accessory...
11/11/2020, 15:31:05 [Viomi V3] INF createRoom | undefined | Room Living room (0) undefined
11/11/2020, 15:31:05 [Viomi V3] INF createRoom | undefined | Room Entrance (1) undefined
11/11/2020, 15:31:05 [Viomi V3] INF createRoom | undefined | Room Kitchen (2) undefined
11/11/2020, 15:31:05 [Viomi V3] INF createRoom | undefined | Room Master bedroom (3) undefined
11/11/2020, 15:31:05 [Viomi V3] INF createRoom | undefined | Room Bedroom (4) undefined
11/11/2020, 15:31:05 HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.
11/11/2020, 15:31:05 HAP Warning: Characteristic 000000AB-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000040-0000-1000-8000-0026BB765291. Adding anyway.

**Comment by GunnarBaldursson** [comment]
11/11/2020, 15:46:46 [Viomi V3] STA getDevice | Serialnumber: Unknown undefined
11/11/2020, 15:46:46 [Viomi V3] INF getFirmware | viomi.vacuum.v13 | Firmwareversion is 3.5.8_0008 undefined
11/11/2020, 15:46:46 [Viomi V3] STA getDevice | Firmwareversion: 3.5.8_0008 undefined
11/11/2020, 15:46:46 [Viomi V3] INF changedCleaning | viomi.vacuum.v13 | Cleaning is OFF. undefined
11/11/2020, 15:46:46 [Viomi V3] MON changedCharging | viomi.vacuum.v13 | ChargingState is now false undefined
11/11/2020, 15:46:46 [Viomi V3] INF changedCharging | viomi.vacuum.v13 | Charging is cancelled undefined
11/11/2020, 15:46:46 [Viomi V3] INF changedCharging | viomi.vacuum.v13 | Robot not anymore in dock. undefined
11/11/2020, 15:46:46 [Viomi V3] INF changedPause | viomi.vacuum.v13 | Paused not possible, no cleaning undefined
11/11/2020, 15:46:49 [Viomi V3] INF getFirmware | viomi.vacuum.v13 | Firmwareversion is 3.5.8_0008 undefined
11/11/2020, 15:46:53 [LgWebOsTv] Device: 192.168.0.80 LG TV, get current Power state successfull, state: OFF
11/11/2020, 15:46:53 [Viomi V3] INF getCleaning | viomi.vacuum.v13 | Cleaning is false undefined
11/11/2020, 15:46:53 [broadlinkPlatformOutlet] checking status for MP1S1
11/11/2020, 15:46:53 [broadlinkPlatformOutlet] checking status for MP1S4
11/11/2020, 15:46:53 [broadlinkPlatformOutlet] checking status for MP1S2
11/11/2020, 15:46:53 [broadlinkPlatformOutlet] checking status for MP1S3
11/11/2020, 15:46:53 [Viomi V3] INF getSpeed | viomi.vacuum.v13 | Fanspeed is null over miIO. Converting to HomeKit undefined
11/11/2020, 15:46:53 [Viomi V3] INF getBatteryLow | viomi.vacuum.v13 | Batterylevel is -1% undefined
11/11/2020, 15:46:53 [Viomi V3] INF getPauseState | viomi.vacuum.v13 | Pause possible is false undefined
11/11/2020, 15:46:53 [broadlinkPlatformOutlet] MP1S1 power is on - true
11/11/2020, 15:46:54 [broadlinkPlatformOutlet] MP1S4 power is on - true
11/11/2020, 15:46:54 [broadlinkPlatformOutlet] MP1S2 power is on - false
11/11/2020, 15:46:54 [broadlinkPlatformOutlet] MP1S3 power is on - true
11/11/2020, 15:47:18 [Viomi V3] INF getCleaning | viomi.vacuum.v13 | Cleaning is false undefined
11/11/2020, 15:47:18 [Viomi V3] INF getBatteryLow | viomi.vacuum.v13 | Batterylevel is -1% undefined
11/11/2020, 15:47:19 [Viomi V3] INF getPauseState | viomi.vacuum.v13 | Pause possible is false undefined
11/11/2020, 15:47:21 [Viomi V3] ACT setCleaning | viomi.vacuum.v13 | Start cleaning Room ID 2, not charging. undefined
11/11/2020, 15:47:22 [Viomi V3] ERR setCleaning | viomi.vacuum.v13 | Failed to set cleaning to true Error: Could not complete call to device
    at checkResult (/home/hoobs/.hoobs/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/checkResult.js:9:11)
    at async XiaomiRoborockVacuum.setCleaningRoom (/home/hoobs/.hoobs/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:917:9)
    at async module.exports (/home/hoobs/.hoobs/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:20)
11/11/2020, 15:47:24 [Viomi V3] ERR setPauseState | viomi.vacuum.v13 | Failed updating pause state true. Error: Could not complete call to device
    at checkResult (/home/hoobs/.hoobs/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/checkResult.js:9:11)
    at async XiaomiRoborockVacuum.setPauseState (/home/hoobs/.hoobs/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:1353:9)
    at async module.exports (/home/hoobs/.hoobs/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:20)
11/11/2020, 15:47:58 [Viomi V3] ERR setPauseState | viomi.vacuum.v13 | Failed updating pause state true. Error: Could not complete call to device
    at checkResult (/home/hoobs/.hoobs/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/checkResult.js:9:11)
    at async XiaomiRoborockVacuum.setPauseState (/home/hoobs/.hoobs/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:1353:9)
    at async module.exports (/home/hoobs/.hoobs/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:20)
11/11/2020, 15:48:05 [Viomi V3] INF getCleaning | viomi.vacuum.v13 | Cleaning is false undefined
11/11/2020, 15:48:05 [Viomi V3] INF getSpeed | viomi.vacuum.v13 | Fanspeed is null over miIO. Converting to HomeKit undefined
11/11/2020, 15:48:07 [Viomi V3] INF getSpeed | viomi.vacuum.v13 | Fanspeed is null over miIO. Converting to HomeKit undefined
11/11/2020, 15:48:07 [Viomi V3] ACT setCleaning | viomi.vacuum.v13 | Start cleaning, not charging. undefined
11/11/2020, 15:48:08 [Viomi V3] ERR setCleaning | viomi.vacuum.v13 | Failed to set cleaning to true Error: Could not complete call to device
    at checkResult (/home/hoobs/.hoobs/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/checkResult.js:9:11)
    at async XiaomiRoborockVacuum.setCleaning (/home/hoobs/.hoobs/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:891:9)
    at async module.exports (/home/hoobs/.hoobs/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:20)

**Comment by WojtekWro** [comment]
Hi @afharo 

I need your help. I have done everything what I could to do. I tried every idea or tip which I found in this place however I got stuck therfore only you can help me :-) 

Room cleaning doesn't work correctly. Behaviour is preaty the same as in prevously mentionet cases. 

Robot starts room cleaning after switching on from Home app and imediately stops and goes back to the dock. In xiaomi app works fine. 

Here is an extract from my log. 
[12/1/2020, 14:27:48] [Robot Piętro] INF getSpeed | viomi.vacuum.v7 | Fanspeed is 3 over miIO. Converting to HomeKit 
[12/1/2020, 14:27:48] [Robot Piętro] INF getSpeed | viomi.vacuum.v7 | Fanspeed is 3 over miIO "Turbo" > HomeKit speed 100% 
[12/1/2020, 14:27:52] [Robot Piętro] ACT setCleaningRoom | viomi.vacuum.v7 | Enable cleaning Room ID 0. 
[12/1/2020, 14:28:06] [Robot Piętro] ACT setSpeed | viomi.vacuum.v7 | FanSpeed set to 1 over miIO for "Standard". 
[12/1/2020, 14:28:06] [Robot Piętro] ACT setCleaning | viomi.vacuum.v7 | Set cleaning to true} 
[12/1/2020, 14:28:06] [Robot Piętro] MON changedSpeed | viomi.vacuum.v7 | FanSpeed is now 1% 
[12/1/2020, 14:28:06] [Robot Piętro] INF changedSpeed | viomi.vacuum.v7 | Speed was changed to 1% (Standard), for HomeKit 50% 
[12/1/2020, 14:28:11] [Robot Piętro] ACT setCleaning | viomi.vacuum.v7 | Start rooms cleaning for rooms 0, device is in state cleaning. 
[12/1/2020, 14:28:11] [Robot Piętro] MON changedCharging | viomi.vacuum.v7 | ChargingState is now false 
[12/1/2020, 14:28:11] [Robot Piętro] INF changedCharging | viomi.vacuum.v7 | Charging is cancelled 
[12/1/2020, 14:28:11] [Robot Piętro] INF changedCleaning | viomi.vacuum.v7 | Cleaning is ON. 
[12/1/2020, 14:28:11] [Robot Piętro] ACT setSpeed | viomi.vacuum.v7 | FanSpeed set to 3 over miIO for "Turbo". 
[12/1/2020, 14:28:11] [Robot Piętro] MON changedSpeed | viomi.vacuum.v7 | FanSpeed _is_ now 3% 
[12/1/2020, 14:28:11] [Robot Piętro] INF changedSpeed | viomi.vacuum.v7 | Speed was changed to 3% (Turbo), for HomeKit 100% 
[12/1/2020, 14:28:21] [Robot Piętro] INF changedCleaning | viomi.vacuum.v7 | Cleaning is OFF. 
[12/1/2020, 14:28:54] [Robot Piętro] MON changedCharging | viomi.vacuum.v7 | ChargingState is now true 
[12/1/2020, 14:28:54] [Robot Piętro] INF changedCharging | viomi.vacuum.v7 | Charging is active

**Comment by afharo** [comment]
Hi @WojtekWro, this line in the logs puzzles me:

```
 [12/1/2020, 14:27:52] [Robot Piętro] ACT setCleaningRoom | viomi.vacuum.v7 | Enable cleaning Room ID 0.
```

`Room ID 0` feels very weird. So far we've seen room IDs are in the range 16-35. Although, not sure about the Viomi models. How does your config look like?

**Comment by dmitrybirin** [comment]
Got the same problem with rooms ID, got 4 rooms: 0, 1, 2, 3. At the end, just mindlessly clicking the switch on and off, and saw in the logs:
`ACT setCleaningRoom | roborock.vacuum.s5 | Enable cleaning Room ID 19`, 
even I've got 0-3 in the config. 
So, when I manually set the IDs from the log, when I switching the switches, everything works :thru

**Comment by afharo** [comment]
Interesting behaviour @dmitrybirin, so you say the config printed in the logs had 0, 1, 2, 3, but it got fixed later on internally? 🤔

**Comment by dmitrybirin** [comment]
yep, I can assume, that [here](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/blob/f4baaece9d4e22b83c335fc2dcb6061e78ea7672/index.js#L1071) `val` is an array of `[index, roomName]` instead of `[id, roomName]`. But that's just an assumption -> need proper debugging.
I can try to do the whole thing again with all the logs, if you need.

**Comment by WojtekWro** [comment]
Hi @afharo. Sorry for so late answer. 

This is weird for me to. However I obtained those IDs from semiauto room detection method. 

My config:
{
            "name": "Robot_P",
            "ip": "192.168.8.46",
            "token": "786a644d5251366a30486a394g2g465a",
            "waterBox": false,
            "silent": false,
            "pause": false,
            "pauseWord": "pause",
            "findMe": false,
            "findMeWord": "where are you",
            "dock": false,
            "delay": false,
            "cleanword": "cleaning",
            "roomTimeout": 5,
            "autoroom": false,
            "rooms": [
                {
                    "name": "Łazienka",
                    "id": 0
                }
            ],
            "accessory": "XiaomiRoborockVacuum"
        }

**Comment by WojtekWro** [comment]
Maybe this extract from log will be helpful. 

[Robot] ERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/network.js:519:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'timeout'
}

**Comment by afharo** [comment]
Hi @WojtekWro, I think that extract of the logs is unrelated to the issue. The serial number issue is a known issue for Viomi models: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/216

**Comment by sleepyarmistice** [comment]
I just want to add that I have a similar finding to @dmitrybirin. When I used the semi-automatic method to discover the ids, I got 0,1,2,3,4. If I don’t proceed to define the switches in the config file, though, when I turn each one on I can see the proper ID in the logs.

**Comment by afharo** [comment]
I just looked at this and it's a logging issue. There should be a follow up log showing the actual configuration with the updated IDs. 

As a temporary fix right now, we can hide the initial log entries showing 0,1,2,... when using the "semiautomatic" room mode

**Comment by afharo** [comment]
In recent versions this has been improved. I'll go ahead and close this issue. Feel free to reopen if this is still relevant.
