### ISSUE TITLE
handshake timeout

### ISSUE THREAD

**Issue by BaRaD5** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#301]
Hey! When trying to boot homebridge it will crash saying the following

` AssertionError [ERR_ASSERTION]: iid of linked service '' is undefined on service 'Xiaomi Mi Robot Vaccum 1st Generation'
    at Fan.Service.internalHAPRepresentation (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:645:15)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:972:54
    at Array.map (<anonymous>)
    at Accessory.internalHAPRepresentation (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:972:31)
    at Bridge.Accessory.internalHAPRepresentation (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:979:36)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1075:25)
    at Server.publishBridge (/usr/local/lib/node_modules/homebridge/src/server.ts:201:17)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:171:24
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:170:5)
[11/1/2020, 18:46:40] [Xiaomi Mi Robot Vaccum 1st Generation] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout`

I double checked the IP and the token what can it be?

**Comment by afharo** [comment]
Can you try running this command?

```
miio-vacuum discover --token YOUR_TOKEN                                               
```

It should reply something like the text below:

```
 INFO  Discovering devices. Press Ctrl+C to stop.

Device ID: 96818260
Model info: roborock.vacuum.s5
Address: 192.168.86.23
Token: YOUR_TOKEN via stored token
Support: At least basic
```

If it doesn't identify your model, it might be unsupported or the token may be incorrect.

**Comment by BaRaD5** [comment]
hey @afharo! thank you for responding and going even further to help! 
I ended up formatting the SD card and "reimaging" it. seems to solve this issue and its working fine now 👍 
thank you !
