### ISSUE TITLE
TypeError: Cannot set property 'roomId' of undefined

### ISSUE THREAD

**Issue by normen** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#324]
With the latest update 0.15 I am getting this error, I am using an `autoroom` list with an S5 Roomba.

```
Nov 29 23:09:36 homebridge homebridge[20924]: [2020-11-29 23:09:36] [Staubsauger] ERR getRoomList | Failed getting the Room List. TypeError: Cannot set property 'roomId' of undefined
Nov 29 23:09:36 homebridge homebridge[20924]:     at XiaomiRoborockVacuum.getRoomList (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:1038:55)
Nov 29 23:09:36 homebridge homebridge[20924]:     at XiaomiRoborockVacuum.initializeDevice (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:672:11)
Nov 29 23:09:36 homebridge homebridge[20924]:     at XiaomiRoborockVacuum.connect (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:759:7)
```

**Comment by afharo** [comment]
Fixed in https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.15.1

**Comment by normen** [comment]
Not quite, now this happens:
```
Nov 30 13:26:04 homebridge homebridge[10834]: [2020-11-30 13:26:04] [Staubsauger] ERR setCleaning | roborock.vacuum.s5 | Failed to set cleaning to true Error: Method `app_segment_clean` is not supported
Nov 30 13:26:04 homebridge homebridge[10834]:     at Object.reject (/home/pi/npm-code/homebridge-xiaomi-roborock-vacuum/miio/lib/network.js:506:19)
Nov 30 13:26:04 homebridge homebridge[10834]:     at DeviceInfo.onMessage (/home/pi/npm-code/homebridge-xiaomi-roborock-vacuum/miio/lib/network.js:396:13)
Nov 30 13:26:04 homebridge homebridge[10834]:     at Socket.<anonymous> (/home/pi/npm-code/homebridge-xiaomi-roborock-vacuum/miio/lib/network.js:169:14)
Nov 30 13:26:04 homebridge homebridge[10834]:     at Socket.emit (events.js:314:20)
Nov 30 13:26:04 homebridge homebridge[10834]:     at UDP.onMessage (dgram.js:921:8) {
Nov 30 13:26:04 homebridge homebridge[10834]:   code: -10000
Nov 30 13:26:04 homebridge homebridge[10834]: }
```

**Comment by afharo** [comment]
oh! this looks like something else! Thank you for letting me know! AFAIK, that piece of logic didn't change in recent versions. Does it also fail when testing your PR #326?

**Comment by normen** [comment]
Yes, it fails both on my "main install" when updating normally and in my dev version with my latest changes. Meaning I can't really use the feature I added ;)

**Comment by normen** [comment]
And I guess it does fail there because the logic around setting the rooms changed, maybe some variable isn't set correctly when this is called?

**Comment by afharo** [comment]
yeah... I'll debug it and will try to find out. Thanks again for noticing and sharing

**Comment by afharo** [comment]
I think I fixed it in https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.15.2

**Comment by normen** [comment]
Yes, works now, also with my changes. Cheers!
