### ISSUE TITLE
Path error on Jeedom Homebridge

### ISSUE THREAD

**Issue by chryss44** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#331]
I have try to install : homebridge-xiaomi-roborock-vacuum on Jeedom  with success but have this error on Homebridge Startup.

Is it possible have Help ?

`ERROR LOADING PLUGIN homebridge-xiaomi-roborock-vacuum:
[12/2/2020, 11:51:41 PM] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
at validateString (internal/validators.js:120:11)
at Object.join (path.js:1039:7)
at userData (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/appdirectory/lib/appdirectory.js:21:29)
at AppDirectory._setTemplates (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/appdirectory/lib/appdirectory.js:134:34)
at new AppDirectory (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/node_modules/appdirectory/lib/appdirectory.js:129:10)
at Object.<anonymous> (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/tokens.js:8:14)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)`

**Comment by afharo** [comment]
Wow! That's an error in an internal dependency. What version of NodeJS are you running?

**Comment by chryss44** [comment]
NodeJS v12.20.0

**Comment by afharo** [comment]
oh! I see the error. That library is relying on the environment variables `XDG_DATA_HOME` or `HOME` to define a path where it should store the token. Do you mind setting any of them to the path where the data should be store (typically `HOME` should be something around `/home/{username}` or `/root` if running as `sudo`).

I'll work on a future release to catch this error and move on anyway since we can always read it from the config.

**Comment by chryss44** [comment]
Yes, i can, but can you help me ?
 Sure it's root execution

**Comment by afharo** [comment]
> can you help me ?

I can try... Although I'm not sure how Jeedom starts Homebridge internally. The whole thing is to find where the command `/usr/{something}/bin/homebridge` is run and prepend `HOME=/root ` in front of that command (mind the final space).

**Comment by chryss44** [comment]
I don't kwon too :-), but can search

**Comment by chryss44** [comment]
The starting Script on Jeedom : 
`#!/usr/bin/env node

//
// This executable sets up the environment and runs the HomeBridge CLI.
//

"use strict";

process.title = "homebridge";

// Find the HomeBridge lib
const path = require("path");
const fs = require("fs");
const lib = path.join(path.dirname(fs.realpathSync(__filename)), "../lib");

// Run HomeBridge
require(lib + '/cli')();
`

**Comment by chryss44** [comment]
I don't know where put the variable HOME on this script, and is it possible ?

**Comment by afharo** [comment]
cool! you can either set the `HOME=/root ` prefix to the place that calls that file or you can add the following line right on top of the `process.title` bit:

```
"use strict";

process.env.HOME = "/root";

process.title = "homebridge";
```

I think either options will work :)

**Comment by chryss44** [comment]
It work with 

```
"use strict";

process.env.HOME = "/root";

process.title = "homebridge";
```

```
[12/3/2020, 8:21:23 PM] Loaded plugin: homebridge-xiaomi-roborock-vacuum@0.16.0
[12/3/2020, 8:21:23 PM] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
[12/3/2020, 8:21:23 PM] ---
[12/3/2020, 8:21:23 PM] Loading 3 platforms...
[12/3/2020, 8:21:23 PM] [House] Initializing Jeedom platform...
[12/3/2020, 8:21:23 PM] [House] debugLevel:400
[12/3/2020, 8:21:24 PM] [Config] Initializing config platform...
[12/3/2020, 8:21:24 PM] [Config] Spawning homebridge-config-ui-x with PID 22079
[12/3/2020, 8:21:24 PM] [Camera-ffmpeg] Initializing Camera-ffmpeg platform...
[12/3/2020, 8:21:24 PM] [Camera-ffmpeg] [Cam Dom 1] Configuring cached bridged accessory...
[12/3/2020, 8:21:24 PM] [Camera-ffmpeg] [Cam Dom PTZ] Configuring cached bridged accessory...
[12/3/2020, 8:21:24 PM] [Camera-ffmpeg] [Door intercom] Configuring cached bridged accessory...
[12/3/2020, 8:21:24 PM] [Camera-ffmpeg] [Wanscam-01] Configuring cached bridged accessory...
[12/3/2020, 8:21:24 PM] [House] Synchronisation Jeedom <> Homebridge...
```

Thank's lot
When do you work on your next release and do you insert correction to not necessary change homebridge start script ?

**Comment by afharo** [comment]
I'll try to fix it this weekend. I can't promise anything though. It's a very deep dependency and I need to double-check any side effects ;)

I'll update on this issue when I release a version that fixes it.

**Comment by chryss44** [comment]
Just for help
Homebridge script on jeedom is here : /var/www/html/plugins/homebridge/resources/node_modules/homebridge/bin#

**Comment by afharo** [comment]
Thank you! I'm planning to get rid of the module `appdirectory` to avoid those inconsistencies. I won't be messing up with Jeedom's setup. 

Apologies for being dormant with this... I've had a few crazy weeks...

**Comment by afharo** [comment]
I think I already removed this... I'll close this issue. Feel free to reopen if this is still relevant
