### ISSUE TITLE
Error connexion with vacuum with python plugin domoticz

### ISSUE THREAD

**Issue by Faaab68** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#352]
Hello can you help me please?

I follow tutorial Xiaomi Mi Robot Vacuum - Domoticz Python plugin
 step by step but i have errors when i put command :

sudo ./miio_server.py 192.168.1.11 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --host 127.0.0.1 --port 22222
 

i have : 
pi@raspberrypi:~/domoticz/plugins/xiaomi-mirobot $ sudo ./miio_server.py 192.168.1.11 XXXXXXXXXXXXXXXXXXXXXXXX --host 127.0.0.1 --port 22222
Traceback (most recent call last):
  File "./miio_server.py", line 17, in <module>
    from miio import Vacuum, DeviceException
  File "././.env/lib/python3.7/site-packages/miio/__init__.py", line 2, in <module>
    from miio.protocol import Message, Utils
  File "././.env/lib/python3.7/site-packages/miio/protocol.py", line 155, in <module>
    Const(Int16ub, 0x2131),
  File "././.env/lib/python3.7/site-packages/construct/core.py", line 2504, in __init__
    super(Const, self).__init__(subcon)
  File "././.env/lib/python3.7/site-packages/construct/core.py", line 670, in __init__
    raise TypeError("subcon should be a Construct field")
TypeError: subcon should be a Construct field

Cand you help me please?
Thanks

**Comment by afharo** [comment]
Sorry, we don't support the Python plugin here. Do you mind opening the issue in their repo? https://github.com/rytilahti/python-miio
