### ISSUE TITLE
Timeout for Serial Number

### ISSUE THREAD

**Issue by Knilo** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#353]
Plugin still works but this always appears in Homebridge logs. I can still control the vacuum but curious about this error. Thanks in advance!

```
ERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/network.js:519:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'timeout'
}
```

**Comment by afharo** [comment]
Hi @Knilo, is your model a Viomi device? If so, it's a known bug: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/216 🙃

**Comment by Knilo** [comment]
Ah my bad! Thanks
