### ISSUE TITLE
"code":"timeout" error message

### ISSUE THREAD

**Issue by misanthrophy** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#367]
Hi,

since the latest update I have multiples times a day these error messages in my log:

`[24.2.2021, 11:00:52] [Wall-e] ERR getState | {"code":"timeout"}
[24.2.2021, 11:01:22] [Wall-e] ERR getState | {"code":"timeout"}`

The roborock is online in the xiaomi App and I can use it on the home app.

**Comment by mrskycriper** [comment]
Same problem

**Comment by afharo** [comment]
Hmm, it looks like a network issue to me. However, I'm working on improving the communication layer #334 

Hopefully, that'll help in the future.

**Comment by WojtekWro** [comment]
I don't know if this is the same but I have still red coloured error :-(
[3/4/2021, 19:19:08] [Robot Piętro] ERR getState | {"code":"timeout","device":null}
[3/4/2021, 19:19:38] [Robot Piętro] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout

**Comment by vskal** [comment]
Hi and thanks for the great work !
I also started getting the following similar error for the last couple of days

[Roborock] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout

However the device is connected and properly operating with Mi Home App.

**Comment by afharo** [comment]
While I get the fix done, does restarting `homebridge` fix the issues to y'all? That's usually the case for most other folks.

**Comment by WojtekWro** [comment]
Yes. Restarting helps. But I need to repeat restart every day. Now I'm looking for solutions to do this automatically.

**Comment by afharo** [comment]
If restarting helps, I think my changes in #334 will fix this (hopefully). I need to fully test it and makes sure it works as expected before releasing it :)

**Comment by uluozgur** [comment]
Hello @afharo, many thanks for your time and efforts. This has just happened to me. While on a cleaning cycle, the timeout errors has started. (see partial logs below) Then I had restarted home bridge but nothing changed, than I have turned off-on via the power button on S5Max and home bridge timeouts stopped but still Homekit was not recognizing the Roborock. Then I have restarted home bridge and it is OK. Don't know where is the problem but Mihome was functioning properly.

**[3/14/2021, 9:56:14 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ERR getState | {"code":"timeout"}**
[3/14/2021, 9:56:30 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaningRoom | roborock.vacuum.s5e | Disable cleaning Room ID 18.
[3/14/2021, 9:56:30 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaningRoom | roborock.vacuum.s5e | Start timeout to clean rooms
[3/14/2021, 9:56:30 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaningRoom | roborock.vacuum.s5e | Disable cleaning Room ID 19.
[3/14/2021, 9:56:30 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaningRoom | roborock.vacuum.s5e | Start timeout to clean rooms
[3/14/2021, 9:56:30 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaningRoom | roborock.vacuum.s5e | Disable cleaning Room ID 16.
[3/14/2021, 9:56:30 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaningRoom | roborock.vacuum.s5e | Start timeout to clean rooms
[3/14/2021, 9:56:30 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaningRoom | roborock.vacuum.s5e | Disable cleaning Room ID 22.
[3/14/2021, 9:56:30 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaningRoom | roborock.vacuum.s5e | Start timeout to clean rooms
[3/14/2021, 9:56:30 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaningRoom | roborock.vacuum.s5e | Disable cleaning Room ID 21.
[3/14/2021, 9:56:30 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaningRoom | roborock.vacuum.s5e | Start timeout to clean rooms
[3/14/2021, 9:56:30 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaningRoom | roborock.vacuum.s5e | Disable cleaning Room ID 17.
[3/14/2021, 9:56:30 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaningRoom | roborock.vacuum.s5e | Start timeout to clean rooms
[3/14/2021, 9:56:31 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaningRoom | roborock.vacuum.s5e | Enable cleaning Room ID 23.
[3/14/2021, 9:56:31 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaningRoom | roborock.vacuum.s5e | Start timeout to clean rooms
[3/14/2021, 9:56:31 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaningRoom | roborock.vacuum.s5e | Enable cleaning Room ID 20.
[3/14/2021, 9:56:31 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaningRoom | roborock.vacuum.s5e | Start timeout to clean rooms
[3/14/2021, 9:56:31 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaningRoom | roborock.vacuum.s5e | Enable cleaning Room ID 24.
[3/14/2021, 9:56:31 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaningRoom | roborock.vacuum.s5e | Start timeout to clean rooms
[3/14/2021, 9:56:31 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaningRoom | roborock.vacuum.s5e | Enable cleaning Room ID 25.
[3/14/2021, 9:56:31 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaningRoom | roborock.vacuum.s5e | Start timeout to clean rooms
[3/14/2021, 9:56:34 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaning | roborock.vacuum.s5e | Set cleaning to true}
**[3/14/2021, 9:56:44 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ERR getState | {"code":"timeout"}
[3/14/2021, 9:56:46 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ERR setCleaning | roborock.vacuum.s5e | Failed to set cleaning to true Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/network.js:519:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'timeout'
}
(node:2534) UnhandledPromiseRejectionWarning: Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/network.js:519:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2534) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2534) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**

**[3/14/2021, 9:57:05 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ERR setCleaning | roborock.vacuum.s5e | Failed to set cleaning to true Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/network.js:519:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'timeout'
}
(node:2534) UnhandledPromiseRejectionWarning: Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/network.js:519:23)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:2534) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[3/14/2021, 9:57:14 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ERR getState | {"code":"timeout"}
[3/14/2021, 9:57:44 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ERR getState | {"code":"timeout"}**
[3/14/2021, 9:57:56 AM] [Homebridge UI] Homebridge restart request received

**Comment by afharo** [comment]
I've published https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.18.0. Hopefully it'll fix these issues.
