### ISSUE TITLE
ERR, Could not find a timer for autoroom 

### ISSUE THREAD

**Issue by kikher** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#370]
Hello, I have a roborock S5 max and in the xiaomi app I create a schedule at 00:00 and I always get an error, it cannot find the timer.
![FCE94415-040F-4A58-A9BD-F1B7C09462D0](https://user-images.githubusercontent.com/75734843/109560482-3bd2da00-7adc-11eb-84a1-ca82fad34a4b.jpeg)

**Comment by kikher** [comment]
Does anyone have a current solution or tutorial to perform the room creation process?

**Comment by afharo** [comment]
Question: did you remember to disable to timer after creating it?

**Comment by kikher** [comment]
yes, I disabled it, what I did is the following.
I opened xiaomi app, I touch the vacuum cleaner button, I touch the three points on the top right, I touch on schedules and create one at 00:00, repeat once, clean mode customize and there I select the map and the rooms in order that I have put in the json. I accept the schedule and deactivate it.
and when i restart homebridege i get that error.
What can I do to make it work?

**Comment by afharo** [comment]
@kikher maybe it's related to a new way the robot is responding, so we fail to parse the timer 🤷 

Do you mind running `homebridge` with the following environment variable `DEBUG="miio:*,thing:*"`? It prints all the raw responses from the robot and really helps us identify any differences.

If you run `homebridge` by command, you can simply run it like `DEBUG="miio:*,thing:*" homebridge` to start it.

**Comment by kikher** [comment]
I do not know how to do that. i have homebridge installed with homebrdge image. https://github.com/homebridge/homebridge-raspbian-image
If you tell me how to do it, I will help you and give all the information you need.
I am Spanish in case you want to give me a guideline in our language.

**Comment by afharo** [comment]
It looks like that image already has the `DEBUG` environment variable exposed in the Homebridge UI: https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Enable-Debug-or-Insecure-Mode. I think you can simply set `miio:*,thing:*` in the box next to `DEBUG`, save and restart the service.

>  I am Spanish in case you want to give me a guideline in our language.

Happy to speak in Spanish if it makes it easier for you 😇. Otherwise, I'll keep it in English for other folks that may come later having the same issue :)

**Comment by kikher** [comment]
I have done what you tell me above, here is what appears in the registry.
If you need more to help me, tell me what you need and I'll give it to you.
<img width="1177" alt="Captura de pantalla 2021-03-06 a las 17 08 52" src="https://user-images.githubusercontent.com/75734843/110213137-0f81d980-7e9f-11eb-89b8-2b2d95530d1b.png">

**Comment by afharo** [comment]
@kikher thank you! Also for finding and sharing the relevant piece of the logs.

As you see, we request the `get_timer` method, and the answer is an empty list `result: []`. We might need to find out why that model replies with an empty list when the timer actually exists (as you claim it does). Sometimes it's just that Xiaomi decides to use a different method (but finding what that new method is is usually tricky).

**Comment by kikher** [comment]
If you tell me how I can help you, I will send you everything you need.  on how to find the new method, or anything from the Xiaomi App or homebridge logs.

**Comment by kikher** [comment]
here is the proof that it is created.
![D0715A25-1D63-4ADE-946A-6E3EBC1EED33](https://user-images.githubusercontent.com/75734843/110364186-c028de00-8043-11eb-83d2-91a96c1f5499.png)

**Comment by afharo** [comment]
It's really puzzling... I can see you've got 2 timers. So `get_timer` should show them both. But it's returning an empty array... I might need to find out what's going on.

**Comment by kikher** [comment]
I am at your disposal for whatever you need

**Comment by thanneman** [comment]
@afharo I’m having the same issue if you need additional information

**Comment by fallenartist** [comment]
Is there any logic for `id` of a room? If I know my room names, then maybe it's worth trying out a few numbers and see if it works? What's your experience? Could anyone share their auto-assigned room ids to see if they would work for others? Ta.

```
"rooms": [
    {
      "id": 16,
      "name": "Livingroom"
    },
    {
      "id": 17,
      "name": "Kitchen"
    }
  ],
```

**Comment by nicolasbigot** [comment]
Same issue here, using a S5 Max vacuum
`ERR setCleaning | roborock.vacuum.s5e | Failed to set cleaning to true Error: data for segment is not a number
    at /homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:255:17
    at DeviceInfo._retryOnTimeout (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:282:24)
    at DeviceInfo.call (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at XiaomiRoborockVacuum.setCleaning (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:903:11) {
  code: -10005
}`

**Comment by kottkrig** [comment]
Same issue here as well.

```
[4/16/2021, 7:51:35 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ERR getRoomList | roborock.vacuum.s6 | Could not find a timer for autoroom
```

However, the rooms get created and I can see them in Homebridge UI and in Homekit. But when I toggle the room to start cleaning them it throws the following error:

```
[4/16/2021, 8:00:48 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ERR setCleaning | roborock.vacuum.s6 | Failed to set cleaning to true Error: data for segment is not a number
    at /usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:255:17
    at DeviceInfo._retryOnTimeout (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:282:24)
    at DeviceInfo.call (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at XiaomiRoborockVacuum.setCleaning (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:903:11) {
  code: -10005
}
```

My config looks like this:

```
    "accessories": [
        {
            "name": "Xiaomi Mi Robot Vaccum 1st Generation",
            "ip": "192.168.1.xxx",
            "token": "xxxxxx",
            "waterBox": false,
            "silent": false,
            "pause": false,
            "pauseWord": "pause",
            "findMe": false,
            "findMeWord": "where are you",
            "dock": true,
            "cleanword": "Dammsug",
            "roomTimeout": 5,
            "autoroom": [
                "Vardagsrum",
                "Hall",
                "Kök",
                "Matsal",
                "Otis rum"
            ],
            "accessory": "XiaomiRoborockVacuum"
        }
    ],
```

**Comment by kottkrig** [comment]
And with the debug command mentioned earlier in the thread:

```
2021-04-16T06:33:36.521Z thing:miio:321632781 -> (5) {"id":4,"method":"get_timer","params":[]}
2021-04-16T06:33:36.521Z miio:packet -> <Buffer 21 31 00 50 00 00 00 00 13 2b ba 0d 60 79 2f c0 33 21 5e 0d 68 e9 6a c4 27 e8 9d cf 15 88 ac 12>
2021-04-16T06:33:36.527Z miio:packet <- <Buffer 21 31 00 40 00 00 00 00 13 2b ba 0d 60 79 2f c0 ba 86 d5 88 3e 33 bf 3c 3c 36 94 56 d5 9d 62 98>
2021-04-16T06:33:36.527Z miio:packet <- <Buffer 21 31 00 40 00 00 00 00 13 2b ba 0d 60 79 2f c0 ba 86 d5 88 3e 33 bf 3c 3c 36 94 56 d5 9d 62 98>
2021-04-16T06:33:36.527Z thing:miio:321632781 <- Message: `{"result":[],"id":4}`
[4/16/2021, 8:33:36 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ERR getRoomList | roborock.vacuum.s6 | Could not find a timer for autoroom
```

And when toggling a room:

```
[4/16/2021, 8:26:03 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ACT setCleaning | roborock.vacuum.s6 | Set cleaning to true}
2021-04-16T06:26:03.233Z thing:miio:321632781 -> (5) {"id":17,"method":"app_segment_clean","params":["2"]}
2021-04-16T06:26:03.233Z miio:packet -> <Buffer 21 31 00 60 00 00 00 00 13 2b ba 0d 60 79 2d fa 4c 1e e9 18 7b 15 eb 67 79 f5 ea a6 db 30 92 c4>
2021-04-16T06:26:03.239Z miio:packet <- <Buffer 21 31 00 70 00 00 00 00 13 2b ba 0d 60 79 2d fb cb 8b 89 d6 e3 bb 23 d2 f7 e8 e6 73 c4 c9 b3 70>
2021-04-16T06:26:03.239Z miio:packet <- <Buffer 21 31 00 70 00 00 00 00 13 2b ba 0d 60 79 2d fb cb 8b 89 d6 e3 bb 23 d2 f7 e8 e6 73 c4 c9 b3 70>
2021-04-16T06:26:03.239Z thing:miio:321632781 <- Message: `{"error":{"code":-10005,"message":"data for segment is not a number"},"id":17}`
[4/16/2021, 8:26:03 AM] [Xiaomi Mi Robot Vaccum 1st Generation] ERR setCleaning | roborock.vacuum.s6 | Failed to set cleaning to true Error: data for segment is not a number
    at /usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:255:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at DeviceInfo._retryOnTimeout (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:282:24)
    at DeviceInfo.call (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at XiaomiRoborockVacuum.setCleaning (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:903:11) {
  code: -10005
}
```

**Comment by Ghitafjorback** [comment]
I have the same issue - Roborock S6 - Firmware 3.5.8_2700.
Could it be related to the fact that "timer" is now called "schedule" in the app. Maybe get_schedule instead of get_timer...

**Comment by urosch** [comment]
Same issue here - Roborock S5, Firmware version 3.5.8_002034.

`ERR getRoomList | roborock.vacuum.s5 | Could not find a timer for autoroom`

**Comment by urosch** [comment]
> Same issue here - Roborock S5, Firmware version 3.5.8_002034.
> 
> `ERR getRoomList | roborock.vacuum.s5 | Could not find a timer for autoroom`

Actually I got this message today:
`2021-05-01T09:38:02.589Z thing:miio:96884912 -> (5) {"id":4,"method":"get_timer","params":[]}
2021-05-01T09:38:02.590Z miio:packet -> <Buffer 21 31 00 50 00 00 00 00 05 c6 58 b0 60 8d 21 7a 00 f2 b1 59 1e 28 66 98 ff 04 e9 30 01 62 41 07>
2021-05-01T09:38:02.595Z miio:packet <- <Buffer 21 31 00 c0 00 00 00 00 05 c6 58 b0 60 8d 21 7a 16 21 26 d2 11 55 1a f5 7a 92 81 8b 38 fb cb 1a>
2021-05-01T09:38:02.595Z miio:packet <- <Buffer 21 31 00 c0 00 00 00 00 05 c6 58 b0 60 8d 21 7a 16 21 26 d2 11 55 1a f5 7a 92 81 8b 38 fb cb 1a>
2021-05-01T09:38:02.596Z thing:miio:96884912 <- Message: `{"result":[["1619643229820","off",["0 12 1 5 *",["start_clean",{"fan_power":102,"segments":"19,16,17,18","repeat":1,"clean_order_mode":0}]]]],"id":4}`
[5/1/2021, 9:38:02 AM] [DaftPunk] ERR getRoomList | roborock.vacuum.s5 | Could not find a timer for autoroom`
It looks as if the room numbers are in the message, but still no autoroom config is done...

**Comment by jszalek** [comment]
the same issue for S5 Max 3.5.8_1340

**Comment by neonatus1** [comment]
same issue S5 max, anything I can help to help with troubleshooting/debugging?

**Comment by datainajar** [comment]
hey all - I'm seeing the same "ERR getRoomList | roborock.vacuum.s5e | Could not find a timer for autoroom" error. S5 Max. Firmware: 3.5.8_1482
Would be happy to attempt to troubleshoot / debug.

**Comment by afharo** [comment]
@gothma, since you initially developed this feature, would you mind helping out on finding what could be happening?

**Comment by miguelpruivo** [comment]
Same, with S5.

**Comment by miguelpruivo** [comment]
Ok, just found how to fix it (at least with S50). Just remove **all** timers that you have in the Xiaomi app and then add **only** one at 00:00 with the rooms, just like explained in the docs. Restart the Homebridge and everything should be working. You can now re-add your other timers.

**Comment by datainajar** [comment]
Hello,
- I have a Roborock S5 Max (s5e). Firmware: 3.5.8_1482
- Located in Australia.
- Using the “Mi Home” App
- In the “Settings” section of the app I do see “timers” instead I see “schedules”
- I’ve removed all “schedules”
- Created a new “scheduled” for “00:00” and selected all the rooms on the map.
- Saved the “schedule”
- Disabled the “schedule”
- Restart home bridge.
- I see “ERR getRoomList | roborock.vacuum.s5e | Could not find a timer for autoroom” in the home bridge log file.

Can anyone point me in the right direction? I was expecting to see a list of rooms and room ID in the log file…
![IMG_1491](https://user-images.githubusercontent.com/87596453/130232535-6a704945-4b5c-4885-bed5-6fe9e71e70c2.PNG)
![IMG_1492](https://user-images.githubusercontent.com/87596453/130232554-53687684-069a-459f-9f48-7ebd8b609a08.PNG)

**Comment by Einstein2150** [comment]
> Hello,
> 
> * I have a Roborock S5 Max (s5e). Firmware: 3.5.8_1482
> * Located in Australia.
> * Using the “Mi Home” App
> * In the “Settings” section of the app I do see “timers” instead I see “schedules”
> * I’ve removed all “schedules”
> * Created a new “scheduled” for “00:00” and selected all the rooms on the map.
> * Saved the “schedule”
> * Disabled the “schedule”
> * Restart home bridge.
> * I see “ERR getRoomList | roborock.vacuum.s5e | Could not find a timer for autoroom” in the home bridge log file.
> 
> Can anyone point me in the right direction? I was expecting to see a list of rooms and room ID in the log file…

You can try to use the miio-api to read the room-array:

`miiocli vacuum --ip [robo-ip] --token [robo-token] get_room_mapping`

The output will show you the id's like that:

`Running command get_room_mapping
[[16, '396001027979'], [18, '396001027981'], [19, '396001027984'], [20, '396001027985'], [21, '396001027982'], [22, '396001027983'], [23, '396001027986'], [24, '396001028028'], [25, '396001027944']]`

**Comment by kikher** [comment]
> > Hello,
> > 
> > * I have a Roborock S5 Max (s5e). Firmware: 3.5.8_1482
> > * Located in Australia.
> > * Using the “Mi Home” App
> > * In the “Settings” section of the app I do see “timers” instead I see “schedules”
> > * I’ve removed all “schedules”
> > * Created a new “scheduled” for “00:00” and selected all the rooms on the map.
> > * Saved the “schedule”
> > * Disabled the “schedule”
> > * Restart home bridge.
> > * I see “ERR getRoomList | roborock.vacuum.s5e | Could not find a timer for autoroom” in the home bridge log file.
> > 
> > Can anyone point me in the right direction? I was expecting to see a list of rooms and room ID in the log file…
> 
> You can try to use the miio-api to read the room-array:
> 
> `miiocli vacuum --ip [robo-ip] --token [robo-token] get_room_mapping`
> 
> The output will show you the id's like that:
> 
> `Running command get_room_mapping [[16, '396001027979'], [18, '396001027981'], [19, '396001027984'], [20, '396001027985'], [21, '396001027982'], [22, '396001027983'], [23, '396001027986'], [24, '396001028028'], [25, '396001027944']]`

hi i am trying to use termial with that line of code but it tells me that the command cannot be found.
Could you explain how to use miiocli please?

**Comment by Einstein2150** [comment]
> > > Hello,
> > > 
> > > * I have a Roborock S5 Max (s5e). Firmware: 3.5.8_1482
> > > * Located in Australia.
> > > * Using the “Mi Home” App
> > > * In the “Settings” section of the app I do see “timers” instead I see “schedules”
> > > * I’ve removed all “schedules”
> > > * Created a new “scheduled” for “00:00” and selected all the rooms on the map.
> > > * Saved the “schedule”
> > > * Disabled the “schedule”
> > > * Restart home bridge.
> > > * I see “ERR getRoomList | roborock.vacuum.s5e | Could not find a timer for autoroom” in the home bridge log file.
> > > 
> > > Can anyone point me in the right direction? I was expecting to see a list of rooms and room ID in the log file…
> > 
> > 
> > You can try to use the miio-api to read the room-array:
> > `miiocli vacuum --ip [robo-ip] --token [robo-token] get_room_mapping`
> > The output will show you the id's like that:
> > `Running command get_room_mapping [[16, '396001027979'], [18, '396001027981'], [19, '396001027984'], [20, '396001027985'], [21, '396001027982'], [22, '396001027983'], [23, '396001027986'], [24, '396001028028'], [25, '396001027944']]`
> 
> hi i am trying to use termial with that line of code but it tells me that the command cannot be found.
> Could you explain how to use miiocli please?

You have to install it with the Python package manager: `pip3 install python-miio `

**Comment by kikher** [comment]
> > > > Hello,
> > > > 
> > > > * I have a Roborock S5 Max (s5e). Firmware: 3.5.8_1482
> > > > * Located in Australia.
> > > > * Using the “Mi Home” App
> > > > * In the “Settings” section of the app I do see “timers” instead I see “schedules”
> > > > * I’ve removed all “schedules”
> > > > * Created a new “scheduled” for “00:00” and selected all the rooms on the map.
> > > > * Saved the “schedule”
> > > > * Disabled the “schedule”
> > > > * Restart home bridge.
> > > > * I see “ERR getRoomList | roborock.vacuum.s5e | Could not find a timer for autoroom” in the home bridge log file.
> > > > 
> > > > Can anyone point me in the right direction? I was expecting to see a list of rooms and room ID in the log file…
> > > 
> > > 
> > > You can try to use the miio-api to read the room-array:
> > > `miiocli vacuum --ip [robo-ip] --token [robo-token] get_room_mapping`
> > > The output will show you the id's like that:
> > > `Running command get_room_mapping [[16, '396001027979'], [18, '396001027981'], [19, '396001027984'], [20, '396001027985'], [21, '396001027982'], [22, '396001027983'], [23, '396001027986'], [24, '396001028028'], [25, '396001027944']]`
> > 
> > 
> > hi i am trying to use termial with that line of code but it tells me that the command cannot be found.
> > Could you explain how to use miiocli please?
> 
> You have to install it with the Python package manager: `pip3 install python-miio`

Thank you very much I just tried it and it works!  one last question, is there any way to identify the long number with the room?

**Comment by Einstein2150** [comment]
No

**Comment by cgmartin** [comment]
I encountered [this issue](https://github.com/rytilahti/python-miio/issues/1272) when trying to use `miiocli vaccum get_room_mapping` method with a `roborock.vacuum.s5`, where it was returning an empty list of segments.

I used [this workaround](https://github.com/rytilahti/python-miio/issues/1272#issuecomment-1013993167)  to get the segment IDs for the room configuration.

ie. my working config:
```
"accessories": [
        {
            "name": "Xiaomi Mi Robot Vaccum 1st Generation",
            "ip": "192.168.x.x",
            "token": "abcd...",
            "waterBox": false,
            "dustCollection": false,
            "silent": false,
            "pause": false,
            "pauseWord": "pause",
            "findMe": false,
            "findMeWord": "where are you",
            "dock": true,
            "cleanword": "cleaning",
            "roomTimeout": 0,
            "rooms": [
                {
                    "name": "Living Room",
                    "id": 16
                },
                {
                    "name": "Dining Room",
                    "id": 17
                },
                {
                    "name": "Kitchen",
                    "id": 18
                }
            ],
            "accessory": "XiaomiRoborockVacuum"
        }
    ],
```

**Comment by alxalxnet** [comment]
> You can try to use the miio-api to read the room-array:
> 
> `miiocli vacuum --ip [robo-ip] --token [robo-token] get_room_mapping`
> 
> The output will show you the id's like that:
> 
> `Running command get_room_mapping [[16, '396001027979'], [18, '396001027981'], [19, '396001027984'], [20, '396001027985'], [21, '396001027982'], [22, '396001027983'], [23, '396001027986'], [24, '396001028028'], [25, '396001027944']]`


Thanks for this! It really helped!

FOR THOSE WHO CAN'T GET IT TO WORK: As of March 2022, it looks like you need to change the first part of the command from `miiocli vacuum` to `miiocli roborockvacuum`—at least, that's what did it for me.

**Comment by gothma** [comment]
Sorry for the long feedback response delay. One idea I got to get the configuration easier:

It seems rooms are always indexed starting with room id 16 and incrementing. I could use set the rooms to id 16 and up in case no suitable timer was found. This way one would at least be able to find out the correct mapping through trial and error. 

Also I've tested with adding timers before the 00:00 timer and it was still found. However it won't be found if the timer set to active. That was to prevent someone from having a robot starting at midnight. Yet this might leave people stranded during setup so I might remove that check.

Also it would be helpful if someone for whom the semi autoroom feature does not work, can give me the communication that happens with the robot during initialization of homebridge. That should be possible to see by setting the environment variable `DEBUG="miio*,thing*"`. This can be also done in homebridge UI in Homebridge Settings > Environment Variables > DEBUG

**Comment by MariellevDijk** [comment]
I'm also having this issue with the Roborock S5 Max, the schedule trick doesn't work sadly. 

I've been trying to do it manually, with help of the miiocli command.
`miiocli roborockvacuum --ip [ip] --token [token] segment_clean [16]` <- The segments trying from 16 and up, looking on the app which room is highlighted. With the segment id found, you can match the longer id to it. 

That longer id is found by running autorooms and looking in the console for something like this:

INF getRoomMap | roborock.vacuum.s5e | Map is 16,434001043xxx,18,434001043xxx,19,434001043xxx, 21,434001043xxx,22,434001043xxx
INF createRoom | roborock.vacuum.s5e | Room 434001043xxx(16)
INF createRoom | roborock.vacuum.s5e | Room 434001043xxx (18)
INF createRoom | roborock.vacuum.s5e | Room 434001043xxx(19)
INF createRoom | roborock.vacuum.s5e | Room 434001043xxx (21)
INF createRoom | roborock.vacuum.s5e | Room 434001043xxx (22)


After that, you can remove the autorooms from the config.json, and put this piece in, corresponding to above method

```
"rooms": [
              {
                  "name": "Bathroom",
                  "room": 434001043xxx,
                  "id": 16
              },
              {
                  "name": "Living room",
                  "room": 434001043xxx,
                  "id": 18
              },
              {
                  "name": "Hallway",
                  "room": 434001043xxx,
                  "id": 19
              },
              {
                  "name": "Toilet",
                  "room": 434001043xxx,
                  "id": 21
              },
              {
                  "name": "Storage",
                  "room": 434001043xxx,
                  "id": 22
              }
            ],
```

This has worked for me, hopefully it can fix some issues.

**Comment by grmelacz** [comment]
Worked for me too, thanks! Until I added the `"room": <long number>` to the config, the switches were not working though I had the correct `"id"` values set.
