### ISSUE TITLE
Roidmi Eve Plus support

### ISSUE THREAD

**Issue by AlexBomber12** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#379]
Hello,

do you have any plans to add Roidmi Eve vacuum cleaner?
Is that even possible?
Log is below:
[15/03/2021, 01:15:13] [Xiaomi Mi Robot Vaccum] STA getDevice | Connected to: 192.168.10.200
[15/03/2021, 01:15:13] [Xiaomi Mi Robot Vaccum] STA getDevice | Model: roidmi.vacuum.v60
[15/03/2021, 01:15:13] [Xiaomi Mi Robot Vaccum] STA getDevice | State: undefined
[15/03/2021, 01:15:13] [Xiaomi Mi Robot Vaccum] STA getDevice | FanSpeed: undefined
[15/03/2021, 01:15:13] [Xiaomi Mi Robot Vaccum] STA getDevice | BatteryLevel: undefined
[15/03/2021, 01:15:13] [Xiaomi Mi Robot Vaccum] DEB ensureDevice | roidmi.vacuum.v60 | The socket is still on. Reusing it.
[15/03/2021, 01:15:23] [Xiaomi Mi Robot Vaccum] ERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at module.exports.getSerialNumber (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/devices/vacuum.js:179:20)
    at XiaomiRoborockVacuum.getSerialNumber (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:827:28)
    at XiaomiRoborockVacuum.initializeDevice (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:675:24)
    at XiaomiRoborockVacuum.connect (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:755:7) {
  code: 'timeout'
}
[15/03/2021, 01:15:23] [Xiaomi Mi Robot Vaccum] STA getDevice | Serialnumber: Unknown
[15/03/2021, 01:15:23] [Xiaomi Mi Robot Vaccum] DEB ensureDevice | roidmi.vacuum.v60 | The socket is still on. Reusing it.
[15/03/2021, 01:15:23] [Xiaomi Mi Robot Vaccum] INF getFirmware | roidmi.vacuum.v60 | Firmwareversion is 0.7.6_2265
[15/03/2021, 01:15:23] [Xiaomi Mi Robot Vaccum] STA getDevice | Firmwareversion: 0.7.6_2265
[15/03/2021, 01:15:23] [Xiaomi Mi Robot Vaccum] DEB ensureDevice | roidmi.vacuum.v60 | The socket is still on. Reusing it.
[15/03/2021, 01:15:33] [Xiaomi Mi Robot Vaccum] ERR getState | {"code":"timeout"}
[15/03/2021, 01:15:37] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"report","model":"motion","sid":"158d0001d5922c","short_id":5944,"data":"{\"no_motion\":\"300\"}"}
[15/03/2021, 01:15:40] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"report","model":"motion","sid":"158d0001d591c3","short_id":42172,"data":"{\"no_motion\":\"300\"}"}
[15/03/2021, 01:15:43] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"report","model":"motion","sid":"158d0001aea2f2","short_id":28378,"data":"{\"no_motion\":\"300\"}"}
[15/03/2021, 01:16:03] [Xiaomi Mi Robot Vaccum] DEB ensureDevice | roidmi.vacuum.v60 | The socket is still on. Reusing it.
[15/03/2021, 01:16:05] [Xiaomi Mi Robot Vaccum] ERR getState | {"code":-30012}
[15/03/2021, 01:16:33] [Xiaomi Mi Robot Vaccum] DEB ensureDevice | roidmi.vacuum.v60 | The socket is still on. Reusing it.
[15/03/2021, 01:16:35] [Xiaomi Mi Robot Vaccum] ERR getState | {"code":-30012}
[15/03/2021, 01:17:03] [Xiaomi Mi Robot Vaccum] DEB ensureDevice | roidmi.vacuum.v60 | The socket is still on. Reusing it.
[15/03/2021, 01:17:05] [Xiaomi Mi Robot Vaccum] ERR getState | {"code":-30012}
[15/03/2021, 01:17:33] [Xiaomi Mi Robot Vaccum] DEB ensureDevice | roidmi.vacuum.v60 | The socket is still on. Reusing it.
[15/03/2021, 01:17:35] [Xiaomi Mi Robot Vaccum] ERR getState | {"code":-30012}
[15/03/2021, 01:18:03] [Xiaomi Mi Robot Vaccum] DEB ensureDevice | roidmi.vacuum.v60 | The socket is still on. Reusing it.
[15/03/2021, 01:18:05] [Xiaomi Mi Robot Vaccum] ERR getState | {"code":-30012}
[15/03/2021, 01:18:33] [Xiaomi Mi Robot Vaccum] DEB ensureDevice | roidmi.vacuum.v60 | The socket is still on. Reusing it.
[15/03/2021, 01:18:35] [Xiaomi Mi Robot Vaccum] ERR getState | {"code":-30012}
[15/03/2021, 01:19:03] [Xiaomi Mi Robot Vaccum] DEB ensureDevice | roidmi.vacuum.v60 | The socket is still on. Reusing it.
[15/03/2021, 01:19:05] [Xiaomi Mi Robot Vaccum] ERR getState | {"code":-30012}
[15/03/2021, 01:19:33] [Xiaomi Mi Robot Vaccum] DEB ensureDevice | roidmi.vacuum.v60 | The socket is still on. Reusing it.
[15/03/2021, 01:19:35] [Xiaomi Mi Robot Vaccum] ERR getState | {"code":-30012}
[15/03/2021, 01:20:03] [Xiaomi Mi Robot Vaccum] INF ensureDevice | roidmi.vacuum.v60 | The socket was destroyed or not initialised, initialising the device
[15/03/2021, 01:20:03] [Xiaomi Mi Robot Vaccum] DEB getDevice | Discovering vacuum cleaner
[15/03/2021, 01:20:13] [Xiaomi Mi Robot Vaccum] STA getDevice | Connected to: 192.168.10.200
[15/03/2021, 01:20:13] [Xiaomi Mi Robot Vaccum] STA getDevice | Model: roidmi.vacuum.v60
[15/03/2021, 01:20:13] [Xiaomi Mi Robot Vaccum] STA getDevice | State: undefined
[15/03/2021, 01:20:13] [Xiaomi Mi Robot Vaccum] STA getDevice | FanSpeed: undefined
[15/03/2021, 01:20:13] [Xiaomi Mi Robot Vaccum] STA getDevice | BatteryLevel: undefined
[15/03/2021, 01:20:13] [Xiaomi Mi Robot Vaccum] DEB ensureDevice | roidmi.vacuum.v60 | The socket is still on. Reusing it.
[15/03/2021, 01:20:23] [Xiaomi Mi Robot Vaccum] ERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at module.exports.getSerialNumber (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/devices/vacuum.js:179:20)
    at XiaomiRoborockVacuum.getSerialNumber (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:827:28)
    at XiaomiRoborockVacuum.initializeDevice (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:675:24)
    at XiaomiRoborockVacuum.connect (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:755:7)
    at XiaomiRoborockVacuum.ensureDevice (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:784:9)
    at XiaomiRoborockVacuum.getState (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:794:7) {
  code: 'timeout'
}
[15/03/2021, 01:20:23] [Xiaomi Mi Robot Vaccum] STA getDevice | Serialnumber: Unknown
[15/03/2021, 01:20:23] [Xiaomi Mi Robot Vaccum] DEB ensureDevice | roidmi.vacuum.v60 | The socket is still on. Reusing it.
[15/03/2021, 01:20:23] [Xiaomi Mi Robot Vaccum] INF getFirmware | roidmi.vacuum.v60 | Firmwareversion is 0.7.6_2265
[15/03/2021, 01:20:23] [Xiaomi Mi Robot Vaccum] STA getDevice | Firmwareversion: 0.7.6_2265
[15/03/2021, 01:20:23] [Xiaomi Mi Robot Vaccum] DEB ensureDevice | roidmi.vacuum.v60 | The socket is still on. Reusing it.
[15/03/2021, 01:20:33] [Xiaomi Mi Robot Vaccum] DEB ensureDevice | roidmi.vacuum.v60 | The socket is still on. Reusing it.
[15/03/2021, 01:20:33] [Xiaomi Mi Robot Vaccum] ERR getState | {"code":"timeout"}
[15/03/2021, 01:20:35] [Xiaomi Mi Robot Vaccum] ERR getState | {"code":-30012}
[15/03/2021, 01:20:35] [Xiaomi Mi Robot Vaccum] ERR getState | {"code":-30012}
[15/03/2021, 01:20:37] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"report","model":"motion","sid":"158d0001d5922c","short_id":5944,"data":"{\"no_motion\":\"600\"}"}
[15/03/2021, 01:20:40] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"report","model":"motion","sid":"158d0001d591c3","short_id":42172,"data":"{\"no_motion\":\"600\"}"}
[15/03/2021, 01:20:42] [MiAqaraPlatform] [DEBUG][Revc]{"cmd":"report","model":"motion","sid":"158d0001aea2f2","short_id":28378,"data":"{\"no_motion\":\"600\"}"}
[15/03/2021, 01:21:03] [Xiaomi Mi Robot Vaccum] DEB ensureDevice | roidmi.vacuum.v60 | The socket is still on. Reusing it.
[15/03/2021, 01:21:06] [Xiaomi Mi Robot Vaccum] ERR getState | {"code":-30012}

**Comment by avatar25pl** [comment]
I hope it will be possible to add support..I am waiting as well.

**Comment by house55ha** [comment]
Я тоже очень жду !

**Comment by Stewart06** [comment]
Bonjour, ayant acheté dernièrement l’aspirateur robot Roidmi Eve Plus, je voudrais savoir également si il est compatible avec se plugins ?

Hello, having recently bought the Roidmi Eve Plus robot vacuum cleaner, I would also like to know if it is compatible with plugins?

**Comment by scobby** [comment]
i have a eve robot too, could help with debugging.

**Comment by sergmuz** [comment]
Roidmi Eve Plus works through xiaomi miot https://github.com/al-one/hass-xiaomi-miot !

**Comment by Gadgetgram01** [comment]
Xiaomi ROIDMI EVE Plus - Self-Emptying RoboVac w/ Sterilizing System
if you want to know more click here: 
https://www.gadgetgram.com/2021/08/10/xiaomi-roidmi-eve-plus-smart-self-emptying-robovac-w-sterilizing-system/

**Comment by avielc** [comment]
Would like to add - 
I saw Homebridge also has a plugin - 
![image](https://user-images.githubusercontent.com/13572969/139953064-84823a51-c8ad-4cd9-af9d-82d270e30127.png)

Was wondering if it works there too @sergmuz @AlexBomber12 @joeltimothyoh
