### ISSUE TITLE
Error using v0.18.0

### ISSUE THREAD

**Issue by torroa** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#382]
The plugin is working fine on v0.17.1 on my Pi,  Node.js Version | v12.21.0 nom v6.14.11

With v0.18.0 I get this:
[3/15/2021, 7:45:07 PM] ERROR LOADING PLUGIN homebridge-xiaomi-roborock-vacuum:
[3/15/2021, 7:45:07 PM] /usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/network.js:118
  #cacheDevice(device) {
              ^

SyntaxError: Unexpected token '('
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/discovery.js:15:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[3/15/2021, 7:45:07 PM] ====================

**Comment by kfalkiewicz** [comment]
Got same problem. After fresh install on Hoobs and configuration (proper IP address and token) it block the homebridge start. Removing accessory from config fixes the problem, so issue is in generated config for this accessory type.

**Comment by paulw11** [comment]
There is an erroneous `#` on line 118 of `/miio/lib/network.js`

**Comment by afharo** [comment]
Thank you for the report, I was developing on Node v14. I'll fix it to provide retro-compatibility to v12

**Comment by afharo** [comment]
I published v0.18.1 with the fix. Please, let me know if it fixed it for you :)
