### ISSUE TITLE
Viomi vacuum V8 Serial number timeout

### ISSUE THREAD

**Issue by dswarne** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#386]
[2021/03/23, 17:51:21] [homebridge-xiaomi-roborock-vacuum] This plugin slows down Homebridge. The read handler for the characteristic 'Serial Number' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[2021/03/23, 17:51:22] [Xiaomi ] ERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (C:\Users\David\AppData\Roaming\npm\node_modules\homebridge-xiaomi-roborock-vacuum\miio\lib\device_info.js:295:29)
    at DeviceInfo.call (C:\Users\David\AppData\Roaming\npm\node_modules\homebridge-xiaomi-roborock-vacuum\miio\lib\device_info.js:227:12)
    at module.exports.getSerialNumber (C:\Users\David\AppData\Roaming\npm\node_modules\homebridge-xiaomi-roborock-vacuum\miio\lib\devices\viomivacuum.js:141:20)
    at XiaomiRoborockVacuum.getSerialNumber (C:\Users\David\AppData\Roaming\npm\node_modules\homebridge-xiaomi-roborock-vacuum\index.js:827:28)
    at module.exports (C:\Users\David\AppData\Roaming\npm\node_modules\homebridge-xiaomi-roborock-vacuum\lib\callbackify.js:5:20) {
  code: 'timeout'
}

**Comment by olexs** [comment]
Can confirm, having the exact same issue with my viomi.vacuum.v8 as well. It connects correctly and can read most data, but some values generate warnings, then a warning is issued "This plugin is slowing down HomeBridge", and eventually it starts throwing the error:

```
[3/27/2021, 7:54:34 PM] [Mi Robot Vacuum] STA getDevice | Connected to: 192.168.0.12
[3/27/2021, 7:54:34 PM] [Mi Robot Vacuum] STA getDevice | Model: viomi.vacuum.v8
[3/27/2021, 7:54:34 PM] [Mi Robot Vacuum] STA getDevice | State: charging
[3/27/2021, 7:54:34 PM] [Mi Robot Vacuum] STA getDevice | FanSpeed: 3
[3/27/2021, 7:54:34 PM] [Mi Robot Vacuum] STA getDevice | BatteryLevel: 100
[3/27/2021, 7:54:44 PM] [Mi Robot Vacuum] ERR getRoomMap | Failed getting the Room Map. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at XiaomiRoborockVacuum.getRoomMap (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:1069:19)
    at XiaomiRoborockVacuum.initializeDevice (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:670:11)
    at XiaomiRoborockVacuum.connect (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:755:7) {
  code: 'timeout'
}
[3/27/2021, 7:54:44 PM] [Mi Robot Vacuum] ERR connect | miio.device, next try in 2 minutes | Error: Call to device timed out
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getCleaning | viomi.vacuum.v8 | Cleaning is false
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getCareSensors | viomi.vacuum.v8 | Sensors dirtytime is undefined seconds / NaN%.
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getCareFilter | viomi.vacuum.v8 | Filter worktime is undefined seconds / NaN%.
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getCareSideBrush | viomi.vacuum.v8 | Sidebrush worktime is undefined seconds / NaN%.
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getCareSensors | viomi.vacuum.v8 | Sensors dirtytime is undefined seconds / NaN%.
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getCareFilter | viomi.vacuum.v8 | Filter worktime is undefined seconds / NaN%.
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getCareSideBrush | viomi.vacuum.v8 | Sidebrush worktime is undefined seconds / NaN%.
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getCharging | viomi.vacuum.v8 | Charging is true (Status is charging)
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getDocked | viomi.vacuum.v8 | Robot Docked is true (Status is charging)
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getCareSensors | viomi.vacuum.v8 | Sensors dirtytime is undefined seconds / NaN%.
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getCareSensors | viomi.vacuum.v8 | Sensors dirtytime is undefined seconds / NaN%.
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getCareFilter | viomi.vacuum.v8 | Filter worktime is undefined seconds / NaN%.
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getCareFilter | viomi.vacuum.v8 | Filter worktime is undefined seconds / NaN%.
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getCareSideBrush | viomi.vacuum.v8 | Sidebrush worktime is undefined seconds / NaN%.
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getCareSideBrush | viomi.vacuum.v8 | Sidebrush worktime is undefined seconds / NaN%.
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getCareMainBrush | viomi.vacuum.v8 | Mainbrush worktime is undefined seconds / NaN%.
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getCareMainBrush | viomi.vacuum.v8 | Mainbrush worktime is undefined seconds / NaN%.
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getBatteryLow | viomi.vacuum.v8 | Batterylevel is 100%
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getBattery | viomi.vacuum.v8 | Batterylevel is 100%
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getSpeed | viomi.vacuum.v8 | Fanspeed is 3 over miIO. Converting to HomeKit
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getSpeed | viomi.vacuum.v8 | Fanspeed is 3 over miIO "Turbo" > HomeKit speed 100%
[3/27/2021, 7:54:48 PM] [homebridge-xiaomi-roborock-vacuum] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[3/27/2021, 7:54:48 PM] [Mi Robot Vacuum] INF getFirmware | viomi.vacuum.v8 | Firmwareversion is 3.5.3_0017
[3/27/2021, 7:54:51 PM] [homebridge-xiaomi-roborock-vacuum] This plugin slows down Homebridge. The read handler for the characteristic 'Serial Number' was slow to respond! See https://git.io/JtMGR for more info.
[3/27/2021, 7:54:57 PM] [homebridge-xiaomi-roborock-vacuum] This plugin slows down Homebridge. The read handler for the characteristic 'Serial Number' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/27/2021, 7:55:08 PM] [Mi Robot Vacuum] ERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at module.exports.getSerialNumber (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/devices/viomivacuum.js:141:20)
    at XiaomiRoborockVacuum.getSerialNumber (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:827:28)
    at module.exports (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:20) {
  code: 'timeout'
}
```

Some of the INF readouts and warnings also repeat randomly in the log multiple times.

I've had to disable the plugin for now. Hoping this gets fixed soon, this is the first time integrating the vacuum into any sort of automation actually showed signs of working :)

**Comment by Moshe-Morad** [comment]
also having this issue
`Xiaomi Mi Robot Vaccum Mop Pro] ERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at module.exports.getSerialNumber (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/devices/viomivacuum.js:141:20)
    at XiaomiRoborockVacuum.getSerialNumber (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:827:28)
    at module.exports (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:20) {
  code: 'timeout'
}`

**Comment by Essdy** [comment]
I am facing the same issue unfortunately. 
https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/discussions/449
