### ISSUE TITLE
Roborock S7

### ISSUE THREAD

**Issue by cgilis** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#390]
Hi, I get this error lately, btw the automatic room detection also doen't work. Any idea?

Kr,

```
[4/3/2021, 2:15:40 PM] [Roborock S7] ERR getFirmware | Failed getting the firmware version. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at XiaomiRoborockVacuum.getFirmware (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:846:24)
    at module.exports (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:20) {
  code: 'timeout'
}
```

**Comment by cgilis** [comment]
Not having the error anymore
