### ISSUE TITLE
S7 support?

### ISSUE THREAD

**Issue by FranciRoosters** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#397]
Does this plugin work with the S7 model?

**Comment by martijnmnnk** [comment]
Yes, except for rooms

**Comment by FranciRoosters** [comment]
I’m not familiar with this plugin and haven’t used it yet, so what exactly do you mean by “except for room”?

**Comment by lukyer** [comment]
When I fill `rooms` field with IDs from `autoroom` startup log - it creates switches for each room but unfortunately when turned on, error is thrown:
```ERR setCleaning | roborock.vacuum.a15 | Failed to set cleaning to true Error: data for segment is invalid
    at /usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:255:17
    at DeviceInfo._retryOnTimeout (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:282:24)
    at DeviceInfo.call (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at XiaomiRoborockVacuum.setCleaning (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:903:11)
    at module.exports (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:20) {
  code: -10005
}```

**Comment by afharo** [comment]
This issue seems stale. I'll go ahead and close it. Feel free to reopen it if you think there's anything pending to discuss.
