### ISSUE TITLE
Dreame vacuum cleaner not yet recognized

### ISSUE THREAD

**Issue by inqdopieter** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#407]
The brand new Dreame vacuum cleaner (I hope you will support it) - can't get it to work.

These are the logs:

[5/17/2021, 9:15:48 AM] [Dreame Stofzuiger] INF ensureDevice | dreame.vacuum.p2029 | The socket was destroyed or not initialised, initialising the device
[5/17/2021, 9:15:58 AM] [Dreame Stofzuiger] STA getDevice | Connected to: 192.168.68.128
[5/17/2021, 9:15:58 AM] [Dreame Stofzuiger] STA getDevice | Model: dreame.vacuum.p2029
[5/17/2021, 9:15:58 AM] [Dreame Stofzuiger] STA getDevice | State: undefined
[5/17/2021, 9:15:58 AM] [Dreame Stofzuiger] STA getDevice | FanSpeed: undefined
[5/17/2021, 9:15:58 AM] [Dreame Stofzuiger] STA getDevice | BatteryLevel: undefined
[5/17/2021, 9:16:08 AM] [Dreame Stofzuiger] ERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at module.exports.getSerialNumber (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/devices/vacuum.js:179:20)
    at XiaomiRoborockVacuum.getSerialNumber (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:827:28)
    at XiaomiRoborockVacuum.initializeDevice (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:675:24)
    at XiaomiRoborockVacuum.connect (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:755:7)
    at XiaomiRoborockVacuum.ensureDevice (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:784:9)
    at XiaomiRoborockVacuum.getState (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:794:7) {
  code: 'timeout'
}
[5/17/2021, 9:16:08 AM] [Dreame Stofzuiger] STA getDevice | Serialnumber: Unknown
[5/17/2021, 9:16:08 AM] [Dreame Stofzuiger] INF getFirmware | dreame.vacuum.p2029 | Firmwareversion is 3.5.8_1052
[5/17/2021, 9:16:08 AM] [Dreame Stofzuiger] STA getDevice | Firmwareversion: 3.5.8_1052
[5/17/2021, 9:16:18 AM] [Dreame Stofzuiger] ERR getState | {"code":"timeout"}

Any idea if this will supported over time?

**Comment by afharo** [comment]
Today I found the specs here: https://miot-spec.org/miot-spec-v2/instance?type=urn:miot-spec-v2:device:vacuum:0000A006:dreame-mc1808:1

This will simplify the works a lot! 🎉

**Comment by ronlimon** [comment]
nice 👍 
Where do you find this stuff?

**Comment by afharo** [comment]
I actually bought a Xiaomi Fan, and I noticed the `homebridge` plugin for that device pointed to those references, then I played around and found that you can actually find all their specs there 🎉 

Now I just need some time to get on coding and implement this :)

**Comment by majidmostafa** [comment]
Hi Guys,
Please I have an issue with my Dreame Vacuum D9 (dreame.vacuum.p2009) which is dead!! (No interaction, no light, no reaction, ...) before that I have switched my Mi Home account from Singapore to French ( because I wanted to link it with my Alexa :( )
It was fully charged and it have requested me to update the firmeware but after that I disovered that the robot is dead and I tried to reset it but no reaction. from that moment I can't do anything as it is fully Off and no signe of reactvitiy, is like the systeme has been erased or its Soft have been broken due to the firmeware update.
Can you please help me to resolve this issue?
For information, I installed the token extractor and I can see the Vaccum linked in my account Singapore and I can see also its token.
Many thanks for your help and support

**Comment by afharo** [comment]
I found https://www.openhab.org/addons/bindings/miio/#dreame-vacuum-mc1808 that might be able to help us with defining the translation protocol for this model... hopefully I'll find some time soon to write it down... if not, anyone is welcome to create a PR :)
