### ISSUE TITLE
Error: Could not connect to device, handshake timeout

### ISSUE THREAD

**Issue by bbodensieck** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#408]
Hi,

I installed this plugin via homebridge and it worked quite well.

Since a few days I am getting the following error
`[Xiaomi Mi Robot Vaccum] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout`

I checked the token.
I also checked for updates of this plugin.
I had no luck. :-(

Any ideas?

Probably it would make sense to have a look at https://github.com/maxinminax/node-mihome and maybe use it as a dependency?

**Comment by bbodensieck** [comment]
I just found out that my homebridge was in the 5 GHz wifi and my robot in the 2.4 GHz wifi. So it seems like a configuration problem on my side.

**Comment by bsoener** [comment]
I have the same problem now. My Fritzbox is connected to the mesh so I get the same error message. How did you solve the problem?

**Comment by bsoener** [comment]
> I just found out that my homebridge was in the 5 GHz wifi and my robot in the 2.4 GHz wifi. So it seems like a configuration problem on my side.

I have the same problem now. My Fritzbox is connected to the mesh so I get the same error message. How did you solve the problem?

**Comment by Arijuz** [comment]
Same Error here but both (homebridge and roborock) are in 2,4 GHz wifi.

Mesh-Network > Homebridge via Repeater & Roborock via router.
This has been working for months without any trouble but nowerdays I get about 99% of the time...

`[Roborock] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout`

It'll be more than nice if someone could explain how to solve this. Appreciate!

**Comment by afharo** [comment]
@Arijuz does it self-recover? Or do you need to restart?

**Comment by Arijuz** [comment]
@afharo It does self-recover.

**Comment by Arijuz** [comment]
Hi again,

please notice, I am not a programmer, I am new to homebridge and the plugin and new to github...
...so all I can do is to offer the logs, do some research and try to understand what's going on.

Now just to let you know, the logs from the last 2 days, starting with the events on the evening that made me reply to the issue.
I so far only had the handshake timeout, but it looks like there is more to it.
Throughout the days I did not restart the roborock manually and let the fortune do the rest. Now see my error excerpts...

```
[21.2.2022, 22:00:07] [Roborock] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[21.2.2022, 22:02:10] [Roborock] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[21.2.2022, 22:04:12] [Roborock] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[21.2.2022, 22:06:14] [Roborock] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[21.2.2022, 22:08:16] [Roborock] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[21.2.2022, 22:10:18] [Roborock] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
```
```
[22.2.2022, 03:58:30] [Roborock] ERR getState | {"code":"timeout"}
[22.2.2022, 03:59:00] [Roborock] ERR getState | {"code":"timeout"}
```
```
[22.2.2022, 13:18:00] [homebridge-xiaomi-roborock-vacuum] This plugin slows down Homebridge. The read handler for the characteristic 'Serial Number' was slow to respond! See https://git.io/JtMGR for more info.
[22.2.2022, 13:18:00] [homebridge-xiaomi-roborock-vacuum] This plugin slows down Homebridge. The read handler for the characteristic 'Firmware Revision' was slow to respond! See https://git.io/JtMGR for more info.
[22.2.2022, 13:18:00] [Roborock] ERR getState | {"code":"timeout"}
[22.2.2022, 13:18:02] [HomeConnect] Terminated events stream for all appliances: getaddrinfo EAI_AGAIN api.home-connect.com
[22.2.2022, 13:18:02] [HomeConnect] Starting events stream for all appliances
[22.2.2022, 13:18:06] [homebridge-xiaomi-roborock-vacuum] This plugin slows down Homebridge. The read handler for the characteristic 'Serial Number' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[22.2.2022, 13:18:06] [homebridge-xiaomi-roborock-vacuum] This plugin slows down Homebridge. The read handler for the characteristic 'Firmware Revision' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[22.2.2022, 13:18:07] [Roborock] ERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at module.exports.getSerialNumber (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/devices/vacuum.js:189:20)
    at XiaomiRoborockVacuum.getSerialNumber (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:842:28)
    at module.exports (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:20) {
  code: 'timeout'
}
[22.2.2022, 13:18:07] [Roborock] ERR getFirmware | Failed getting the firmware version. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at XiaomiRoborockVacuum.getFirmware (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:861:24)
    at module.exports (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:20) {
  code: 'timeout'
}
```
```
[23.2.2022, 04:01:31] [Roborock] ERR getState | {"code":"timeout"}
[23.2.2022, 04:02:01] [Roborock] ERR getState | {"code":"timeout"}
[23.2.2022, 04:02:31] [Roborock] ERR getState | {"code":"timeout"}
[23.2.2022, 04:03:01] [Roborock] ERR getState | {"code":"timeout"}
[23.2.2022, 04:03:21] [Roborock] INF ensureDevice | roborock.vacuum.a10 | The socket was destroyed or not initialised, initialising the device
[23.2.2022, 04:03:23] [Roborock] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[23.2.2022, 04:03:23] [Roborock] ERR getState | {"code":"timeout","device":null}
[23.2.2022, 04:03:51] [Roborock] INF ensureDevice | roborock.vacuum.a10 | The socket was destroyed or not initialised, initialising the device
[23.2.2022, 04:03:53] [Roborock] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[23.2.2022, 04:03:53] [Roborock] ERR getState | {"code":"timeout","device":null}
[23.2.2022, 04:04:21] [Roborock] INF ensureDevice | roborock.vacuum.a10 | The socket was destroyed or not initialised, initialising the device
[23.2.2022, 04:04:23] [Roborock] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[23.2.2022, 04:04:23] [Roborock] ERR getState | {"code":"timeout","device":null}
[23.2.2022, 04:04:51] [Roborock] INF ensureDevice | roborock.vacuum.a10 | The socket was destroyed or not initialised, initialising the device
[23.2.2022, 04:04:53] [Roborock] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[23.2.2022, 04:04:53] [Roborock] ERR getState | {"code":"timeout","device":null}
[23.2.2022, 04:05:21] [Roborock] INF ensureDevice | roborock.vacuum.a10 | The socket was destroyed or not initialised, initialising the device
```

**Comment by afharo** [comment]
@Arijuz, thanks for the details!

Looking at this other plugin's error:

```
[22.2.2022, 13:18:02] [HomeConnect] Terminated events stream for all appliances: getaddrinfo EAI_AGAIN api.home-connect.com
[22.2.2022, 13:18:02] [HomeConnect] Starting events stream for all appliances
```

It looks to me like there are some connectivity issues in the device running homebridge. If it self-recovers when connectivity is reestablished, I don't think I can help much on my end.

> Mesh-Network > Homebridge via Repeater & Roborock via router.

Probably the repeater is dropping connection from time to time?

**Comment by bsoener** [comment]
I also have partly the same error message. Is there something wrong? A call from the developer would help us a lot. In the issue, the messages pile up but no one does anything.

```
[23/02/2022, 12:01:59] [Xiaomi Roborock] ERR getState | {"code":"timeout"}
[23/02/2022, 12:08:29] [Xiaomi Roborock] ERR getState | {"code":"timeout"}
[23/02/2022, 12:10:29] [Xiaomi Roborock] ERR getState | {"code":"timeout"}
[23/02/2022, 12:10:59] [Xiaomi Roborock] ERR getState | {"code":"timeout"}
[23/02/2022, 12:11:29] [Xiaomi Roborock] ERR getState | {"code":"timeout"}
[23/02/2022, 12:14:29] [Xiaomi Roborock] ERR getState | {"code":"timeout"}
[23/02/2022, 12:15:29] [Xiaomi Roborock] ERR getState | {"code":"timeout"}
[23/02/2022, 12:16:59] [Xiaomi Roborock] ERR getState | {"code":"timeout"}
[23/02/2022, 12:17:29] [Xiaomi Roborock] ERR getState | {"code":"timeout"}
[23/02/2022, 12:17:59] [Xiaomi Roborock] ERR getState | {"code":"timeout"}
[23/02/2022, 12:18:29] [Xiaomi Roborock] ERR getState | {"code":"timeout"}
```

**Comment by afharo** [comment]
Some models fail to report the `getState` call. I'm trying to gather all the models with that issue to stop requesting it for them.
