### ISSUE TITLE
Serial number error

### ISSUE THREAD

**Issue by lexx0006** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#414]
I always get this error message:

----
[homebridge-xiaomi-roborock-vacuum] This plugin slows down Homebridge. The read handler for the characteristic 'Serial Number' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[8.6.2021, 15:43:09] [iRobot] ERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at module.exports.getSerialNumber (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/devices/viomivacuum.js:141:20)
    at XiaomiRoborockVacuum.getSerialNumber (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:827:28)
    at module.exports (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:20) {
  code: 'timeout'
}
----
![Screenshot 2021-06-08 154922](https://user-images.githubusercontent.com/77328672/121196883-20acfe80-c871-11eb-9742-a82c9c2c6673.jpg)

Why the plugin needs the serial number?
My Mi Robot: Mi Robot Vacuum MOP Pro

**Comment by afharo** [comment]
@lexx0006 do you have a Viomi? if so, there's an known error that this plugin cannot get the serial number for that model yet 🤷

**Comment by afharo** [comment]
#358
