### ISSUE TITLE
Roborock S7 room cleaning

### ISSUE THREAD

**Issue by lukyer** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#431]
Hi,
my config is:
```
{
            "name": "xxx",
            "ip": "xxx",
            "token": "xxx",
            "waterBox": false,
            "silent": false,
            "pause": false,
            "pauseWord": "pause",
            "findMe": true,
            "findMeWord": "where are you",
            "dock": true,
            "cleanword": "cleaning",
            "roomTimeout": 1,
            "autoroom": false,
            "rooms": [
                {
                    "name": "Bedroom",
                    "id": 810001005719
                },
                {
                    "name": "Living room",
                    "id": 810001004274
                },
                {
                    "name": "Kitchen",
                    "id": 810001004882
                },
                {
                    "name": "Bathroom",
                    "id": 810001031940
                }
            ],
            "accessory": "XiaomiRoborockVacuum"
        }
```

I set up rooms using `autoroom` startup log message. However when I try to turn on some room switch, it throws exception:

```
ERR setCleaning | roborock.vacuum.a15 | Failed to set cleaning to true Error: data for segment is invalid
    at /usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:255:17
    at DeviceInfo._retryOnTimeout (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:282:24)
    at DeviceInfo.call (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at XiaomiRoborockVacuum.setCleaning (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:903:11) {
  code: -10005
}
```

Any idea how to fix it? I tried `roomTimeout: 1` but with no luck. 
Thanks!

**Comment by Einstein2150** [comment]
The room id is not such a long number. The room id is something like „12“. Can you check the room mapping with miio?

**Comment by Einstein2150** [comment]
You can try to use the miio-api to read the room-array:

`miiocli vacuum --ip [robo-ip] --token [robo-token] get_room_mapping`

The output will show you the id's like that:

`Running command get_room_mapping [[16, '396001027979'], [18, '396001027981'], [19, '396001027984'], [20, '396001027985'], [21, '396001027982'], [22, '396001027983'], [23, '396001027986'], [24, '396001028028'], [25, '396001027944']]`

**Comment by lukyer** [comment]
oh cool that works! Did I miss something in the Readme or should we update it to make it more clear? Thanks!

**Comment by Einstein2150** [comment]
> oh cool that works! Did I miss something in the Readme or should we update it to make it more clear? Thanks!

You can update it. I think it will help lot of users 😄

**Comment by LukasEm** [comment]
Hello, sorry for maybe a stupid question, but how to run command miiocli? I installed miio-api npm but the command you suggested cant be run, what should I install?

**Comment by afharo** [comment]
@LukasEm I think they are referring to https://python-miio.readthedocs.io/en/latest/
