### ISSUE TITLE
Problem with Vacuum Dreame (mc1808)

### ISSUE THREAD

**Issue by PreVory** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#434]
Hello,
Could you please help me with problem?

1. Model: dreame.vacuum.mc1808
2. Firmware: 4.1.8_1118
3. Log:
`[9/3/2021, 1:32:53 PM] [XiaomiRoborockVacuum] STA getDevice | Connected to: 192.168.88.247
[9/3/2021, 1:32:53 PM] [XiaomiRoborockVacuum] STA getDevice | Model: dreame.vacuum.mc1808
[9/3/2021, 1:32:53 PM] [XiaomiRoborockVacuum] STA getDevice | State: undefined
[9/3/2021, 1:32:53 PM] [XiaomiRoborockVacuum] STA getDevice | FanSpeed: undefined
[9/3/2021, 1:32:53 PM] [XiaomiRoborockVacuum] STA getDevice | BatteryLevel: undefined
[9/3/2021, 1:33:03 PM] [XiaomiRoborockVacuum] ERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at module.exports.getSerialNumber (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/devices/viomivacuum.js:141:20)
    at XiaomiRoborockVacuum.getSerialNumber (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:827:28)
    at XiaomiRoborockVacuum.initializeDevice (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:675:24)
    at XiaomiRoborockVacuum.connect (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:755:7) {
  code: 'timeout'
}
[9/3/2021, 1:33:03 PM] [XiaomiRoborockVacuum] STA getDevice | Serialnumber: Unknown
[9/3/2021, 1:33:03 PM] [XiaomiRoborockVacuum] INF getFirmware | dreame.vacuum.mc1808 | Firmwareversion is 4.1.8_1118
[9/3/2021, 1:33:03 PM] [XiaomiRoborockVacuum] STA getDevice | Firmwareversion: 4.1.8_1118
[9/3/2021, 1:33:13 PM] [XiaomiRoborockVacuum] ERR getState | {"code":"timeout"}
[9/3/2021, 1:33:53 PM] [XiaomiRoborockVacuum] ERR getState | {"code":"timeout"}
[9/3/2021, 1:34:23 PM] [XiaomiRoborockVacuum] ERR getState | {"code":"timeout"}
[9/3/2021, 1:34:53 PM] [XiaomiRoborockVacuum] ERR getState | {"code":"timeout"}
[9/3/2021, 1:35:23 PM] [XiaomiRoborockVacuum] ERR getState | {"code":"timeout"}
[9/3/2021, 1:35:53 PM] [XiaomiRoborockVacuum] ERR getState | {"code":"timeout"}
[9/3/2021, 1:36:23 PM] [XiaomiRoborockVacuum] ERR getState | {"code":"timeout"}
[9/3/2021, 1:36:53 PM] [XiaomiRoborockVacuum] ERR getState | {"code":"timeout"}
[9/3/2021, 1:37:23 PM] [XiaomiRoborockVacuum] ERR getState | {"code":"timeout"}`

Also I try to use miio in Python.
My sample:

```
from miio import Vacuum
ip = '192.168.88.247'
token = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
vac = Vacuum(ip, token)
vac.info() // works сorrectly (dreame.vacuum.mc1808 v4.1.8_1118 (DD:DD:DD:FD:BD:AD) @ 192.168.88.247 - token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX)

vac.fan_speed() // return DeviceError: {'code': -9999, 'message': 'user ack timeout'}
```

**Comment by ptath** [comment]
same problem

**Comment by afharo** [comment]
Hi! I'm afraid the Dreame models are not supported by this plugin yet. Related to #407.

I may need some time to implement it. Also, if anyone wants to take a dive and submit a PR, it'd be great!
