### ISSUE TITLE
Support for Viomi S9 (viomi.vacuum.v18)

### ISSUE THREAD

**Issue by birdofhermes** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#443]
Hello

I wanted to add my S9 to the homebridge, and after configuration and set up, all of the "get-device" statuses are remaining undefined and the get state is in status time out

`Starting to advertise 'Homebridge AB27 FFAA' using bonjour-hap backend!
[23/09/2021, 13:07:59] Homebridge v1.3.4 (Homebridge AB27) is running on port 51544.
[23/09/2021, 13:08:09] [Xiaomi Mi Robot Vaccum 1st Generation] STA getDevice | Connected to: 192.168.0.221
[23/09/2021, 13:08:09] [Xiaomi Mi Robot Vaccum 1st Generation] STA getDevice | Model: viomi.vacuum.v18
[23/09/2021, 13:08:09] [Xiaomi Mi Robot Vaccum 1st Generation] STA getDevice | State: undefined
[23/09/2021, 13:08:09] [Xiaomi Mi Robot Vaccum 1st Generation] STA getDevice | FanSpeed: undefined
[23/09/2021, 13:08:09] [Xiaomi Mi Robot Vaccum 1st Generation] STA getDevice | BatteryLevel: undefined
[23/09/2021, 13:08:19] [Xiaomi Mi Robot Vaccum 1st Generation] ERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at module.exports.getSerialNumber (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/devices/viomivacuum.js:141:20)
    at XiaomiRoborockVacuum.getSerialNumber (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:827:28)
    at XiaomiRoborockVacuum.initializeDevice (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:675:24)
    at XiaomiRoborockVacuum.connect (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:755:7) {
  code: 'timeout'
}
[23/09/2021, 13:08:19] [Xiaomi Mi Robot Vaccum 1st Generation] STA getDevice | Serialnumber: Unknown
[23/09/2021, 13:08:20] [Xiaomi Mi Robot Vaccum 1st Generation] INF getFirmware | viomi.vacuum.v18 | Firmwareversion is 1.6.5_2254
[23/09/2021, 13:08:20] [Xiaomi Mi Robot Vaccum 1st Generation] STA getDevice | Firmwareversion: 1.6.5_2254
[23/09/2021, 13:08:30] [Xiaomi Mi Robot Vaccum 1st Generation] ERR getState | {"code":"timeout"}
[23/09/2021, 13:09:10] [Xiaomi Mi Robot Vaccum 1st Generation] ERR getState | {"code":"timeout"}
[23/09/2021, 13:09:40] [Xiaomi Mi Robot Vaccum 1st Generation] ERR getState | {"code":"timeout"}`

**Comment by alephsmith** [comment]
I also have this model and would like to help to get this supported.

**Comment by dirbuf** [comment]
+1 would also like my s9 to be compatible with this plugin

**Comment by afharo** [comment]
Hi! I think [v0.28.0](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.28.0) should fix this issue. I don't have that model. Would you mind testing it out?
