### ISSUE TITLE
Xiaomi ERR Connect

### ISSUE THREAD

**Issue by bsoener** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#444]
Why do I always get this error message? The Ip address is correct, token was checked. Since I have connected my Fritzbox to the mesh, I always get this error. Does anyone know what to do?

[Xiaomi Roborock] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout

**Comment by petaBitsDev** [comment]
+1 Same problem here

**Comment by bsoener** [comment]
```
[17/10/2021, 16:32:22] [Xiaomi Roborock] ERR getFirmware | Failed getting the firmware version. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at XiaomiRoborockVacuum.getFirmware (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:846:24)
    at module.exports (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:20) {
  code: 'timeout'
}
```

**Comment by Donni1966** [comment]
Get the same with my Robos 
`[05/11/2021, 18:06:51] [RobiS5] ERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:295:29)
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:60:5)
    at listOnTimeout (internal/timers.js:526:9)
    at processTimers (internal/timers.js:500:7)
    at DeviceInfo.call (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at module.exports.getSerialNumber (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/devices/vacuum.js:179:20)
    at XiaomiRoborockVacuum.getSerialNumber (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:827:28)
    at module.exports (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:20) {
  code: 'timeout'
}
[05/11/2021, 18:06:51] [RobiS5] ERR getFirmware | Failed getting the firmware version. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at XiaomiRoborockVacuum.getFirmware (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:846:24)
    at module.exports (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:20) {
  code: 'timeout'
}
[05/11/2021, 18:06:51] [RobiS5] ERR getState | {"code":"timeout"}
[05/11/2021, 18:07:22] [RobiS5] ERR getState | {"code":"timeout"}`

**Comment by bsoener** [comment]
I keep getting this error message: 
`[03/01/2022, 19:16:26] [Xiaomi Roborock] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout`

Already tried everything: Roborock reset, wlan...
I think they have no interest to expand the plugin. Will look for another solution. What a pity.

**Comment by afharo** [comment]
I would love to extend the plugin. I just have not as much spare time as I'd like to. Contributions are welcomed via Pull Requests :)

**Comment by bsoener** [comment]
Thank you for your answer. I think if you could solve this problem here it would be great. Because many here have this problem.

**Comment by afharo** [comment]
I'd love to solve this issue for you all. It looks to me like resetting the connection would probably solve it.

However, comments like the one below makes me believe that the issue is somewhere else in the router (most of the folks reporting this issue use the Fritzbox router):

> same here on Xiaowa E Series - used to work until a couple of days ago

If the plugin was not changed in the meanwhile, it shouldn't be the one to blame.

I personally had a similar issue with my carrier's router and it got solved when I bought my own router.

I don't know the internals of that router, but in my case, I knew that BT's routers had host isolation when using 2.4GHz vs 5GHz so sometimes I couldn't see my Chromecast and my raspberry couldn't see the vacuum.

With all that said, we could probably look at this plugin's connection layer to see if we can change the reconnection strategy so it fixes the issue that you all are suffering from.

**Comment by bsoener** [comment]
I bought my own router (7590) I have now tried everything: reset the router and wifi, my robot vacuum completely to factory settings but without success. I would appreciate it if you can take the time to solve this tu. Thank you for the effort and time.

**Comment by bsoener** [comment]
[23/05/2022, 14:15:42] [Xiaomi Roborock] ERR getState | {"code":"timeout"}
(node:23506) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnect listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23506) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 childBridgeStatusUpdate listeners added to [HomebridgeIpcService]. Use emitter.setMaxListeners() to increase limit
(node:23506) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit

**Comment by TeppoTommi** [comment]
I'm having the same issue ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
It worked fine for a few months after setup, but then just stopped working. I've made no changes in my networks setup. Tried to restart and reset plugin and wifi but no help (I don't have a Fritzbox router). Are there any pointers on what is the reason for connection failure or what I could do about it?

**Comment by kornflex** [comment]
Same problem with a xiaomi R3p convert to openwrt and wifi mesh :/

**Comment by afharo** [comment]
> In my case, it occurs as soon as homebridge is started.

@kornflex, if it doesn't connect from the beginning, IMO, this is a different issue from what I've seen in the past.

Are you positive that the token is correct? You can validate it by running the following command:

```sh
miio-vacuum inspect YOUR_IP --token YOUR_TOKEN
```

To fetch the token, I found the easiest and most reliable tool is https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor

**Comment by kornflex** [comment]
> > In my case, it occurs as soon as homebridge is started.
> 
> @kornflex, if it doesn't connect from the beginning, IMO, this is a different issue from what I've seen in the past.
> 
> Are you positive that the token is correct? You can validate it by running the following command:
> 
> ```shell
> miio-vacuum inspect YOUR_IP --token YOUR_TOKEN
> ```
> 
> To fetch the token, I found the easiest and most reliable tool is https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor

Yes I'm sure. I use this token in jeedom and the vacuum works.
It works before I switch to wifi mesh with openwrt.
Before, with the xiaomi r3p router and his stock firmware, all was OK.

**Comment by afharo** [comment]
@kornflex, it sounds like a specific configuration of OpenWRT is blocking the connections, doesn't it?

Is there any specific request the plugin needs to do to OpenWRT to allow it? At the moment, it is connecting to the robot via UDP/datagram sockets: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/blob/757cef36262199676834126ccf29a4e9cb81bdab/src/miio/lib/network.js#L128

Could that be it? That the OpenWRT config is blocking UDP connections?

**Comment by bsoener** [comment]
[31/08/2022, 03:07:44] [Xiaomi Roborock] ERR getState | {"code":"timeout"}

this error message always appears.

**Comment by afharo** [comment]
> [31/08/2022, 03:07:44] [Xiaomi Roborock] ERR getState | {"code":"timeout"}
> 
> this error message always appears.

@bsoener, thanks for confirming 🧡. Then similar questions apply. If it never connects and always shows timeout from the beginning, my gut feeling is not that the plugin has a bug in the connection logic, but something else. IMO, it could be either:

* **Misconfiguration:** Either the IP or the token are wrong. You can validate that they are correct with the command `miio-vacuum inspect YOUR_IP --token YOUR_TOKEN`.
* **Network issue:** It may happen that the router's configuration is blocking the connections (either rejecting UDP packets or isolating each host/subnetwork (some routers have isolated networks for 2.4GHz and 5GHz wifi bands) so the machine where `homebridge` is running cannot reach to the robot and viceversa.
* **Model is not supported yet:** In the past, we've seen the `ERR getState | {"code":"timeout"}` log message for models that are not supported by this plugin yet. Like the Dreame model in this other issue: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/434

According to your original description, the IP, token, and model seem to fit, so I'd look at a potential network issue. Can you validate that running `miio-vacuum inspect YOUR_IP --token YOUR_TOKEN` from the same machine where `homebridge` is running, you get a response?

**Comment by bsoener** [comment]
So the ip and token are correct. Must be something else... It may be that it really is the Fritzbox!?

**Comment by bsoener** [comment]
Good morning Unfortunately, I am out of my depth on this question. This would have to do someone who has more knowledge of it.

**Comment by kornflex** [comment]
> Good morning Unfortunately, I am out of my depth on this question. This would have to do someone who has more knowledge of it.

Hello,
I have updated my openwrt & librairies.
My vaccum always switches between mesh access point, so I have added a mac address blacklist on one of mesh AP.

He always tries to connect but he is quickly rejected. So I don't loose the connection too long.

Homebridge works a little better.

**Comment by afharo** [comment]
@kornflex FWIW, I have a mesh connection at home as well and it just works. I'm using the Google WiFi routers though.

**Comment by bsoener** [comment]
`[02/09/2022, 07:23:09] [homebridge-xiaomi-roborock-vacuum] This plugin slows down Homebridge. The read handler for the characteristic 'Serial Number' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[02/09/2022, 07:23:10] [Xiaomi Roborock] [Model=roborock.vacuum.s6] getSerialNumber | Failed getting the serial number. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/miio/lib/device_info.js:227:12)
    at module.exports.getSerialNumber (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/miio/lib/devices/vacuum.js:193:20)
    at ProductInfo.getSerialNumber (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/product_info.ts:82:28) {
  code: 'timeout'
}`

**Comment by kornflex** [comment]
> @kornflex FWIW, I have a mesh connection at home as well and it just works. I'm using the Google WiFi routers though.

Yes. But in my case, an other plugin, for my domotic, works with this vacuum when I can't use it with homebridge.
If my routeur is in cause, I should be the same problem everywhere...

it's "xiaomi home" plugin for "jeedom"
I don't know how it work. It's python request, but I don't see if it's TCP or UDP.

It's using a xiaomipacket class like this : 
```
class XiaomiPacket():
	def __init__(self,token=''):
		self.magic =      "2131".decode('hex')
		self.length =     "0020".decode('hex')
		self.unknown1 =   "FFFFFFFF".decode('hex')
		self.devicetype = "FFFF".decode('hex')
		self.serial   =   "FFFF".decode('hex')
		self.stamp =      "FFFFFFFF".decode('hex')
		self.checksum =   "ffffffffffffffffffffffffffffffff".decode('hex')
		self.data = ""
		self.token = ""

	def setRaw(self, raw):
		self.magic =      raw[ 0: 2]
		self.length =     raw[ 2: 4]
		self.unknown1 =   raw[ 4: 8]
		self.devicetype = raw[ 8:10]
		self.serial =     raw[10:12]
		self.stamp =      raw[12:16]
		self.checksum =   raw[16:32]
		self.data =       raw[32:]
		if self.length=="0020".decode('hex'):
			self.token=self.checksum
		return
```

**Comment by yangirov** [comment]
When I use command `miio-vacuum inspect YOUR_IP --token YOUR_TOKEN` device not found.

But, when I use [python-miio](https://github.com/rytilahti/python-miio) everything is OK.

Maybe this information will be useful.

![image](https://user-images.githubusercontent.com/32175431/197336352-f72ba6a8-f169-45ac-accd-af8cbab17236.png)

**Comment by yangirov** [comment]
But, device found if i use`miio-vacuum discover --token 437770674578317276634e30574f6168`

![image](https://user-images.githubusercontent.com/32175431/197337208-3acaa261-6506-4041-97fd-1b4068dc06b6.png)

**Comment by afharo** [comment]
@yangirov I think your case is different to the ones above. That model is not supported yet by this plugin. Refer to https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/434 for more info.

**Comment by charlesvestal** [comment]
for what it's worth, on a fritzbox, i am having the same experience as @yangirov 

Token is successfully extracted:
```

charlesvestal@CharlesV-MacBookPro18 ~ % bash <(curl -L https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/raw/master/run.sh)

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
100   292  100   292    0     0     79      0  0:00:03  0:00:03 --:--:--    79
Archive:  token_extractor.zip
   creating: token_extractor/
  inflating: token_extractor/token_extractor.py  
 extracting: token_extractor/requirements.txt  
Requirement already satisfied: requests in /opt/homebrew/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (2.28.1)
Requirement already satisfied: pycryptodome in /opt/homebrew/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (3.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.10/site-packages (from requests->-r requirements.txt (line 1)) (2022.9.24)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.10/site-packages (from requests->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/homebrew/lib/python3.10/site-packages (from requests->-r requirements.txt (line 1)) (1.26.12)
Requirement already satisfied: charset-normalizer<3,>=2 in /opt/homebrew/lib/python3.10/site-packages (from requests->-r requirements.txt (line 1)) (2.1.1)

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: python3.10 -m pip install --upgrade pip
Username (email or user ID):
email@email.com
Password:
xxx
Server (one of: cn, de, us, ru, tw, sg, in, i2) Leave empty to check all available:
de

Logging in...
Logged in.

Devices found for server "de":
   ---------
   NAME:     Mi Robot Vacuum-Mop P
   ID:       309265658
   MAC:      5C:E5:0C:81:8F:6E
   IP:       192.168.178.54
   TOKEN:    4f5571477xxx
   MODEL:    viomi.vacuum.v8
   ---------


Press ENTER to finish
```
and via miiocli

```
charlesvestal@CharlesV-MacBookPro18 ~ % miiocli cloud list
Username: email@email.com
Password: xxx
Locale (cn, de, i2, ru, sg, us, all): de
== Mi Robot Vacuum-Mop P (Device online ) ==
	Model: viomi.vacuum.v8
	Token: 4f5571477xxx
	IP: 192.168.178.54 (mac: 5C:E5:0C:81:8F:6E)
	DID: 309265658
	Locale: de
```

but can't be inspected with miio-vacuum

```
charlesvestal@CharlesV-MacBookPro18 ~ % miio-vacuum inspect 192.168.178.54 --token 4f5571477xxx
 INFO  Attempting to inspect 192.168.178.54
 WARNING  Could not find device
```

and doesn't return device info
```

charlesvestal@CharlesV-MacBookPro18 ~ % miio-vacuum discover --token 4f5571477xxx
 INFO  Discovering devices. Press Ctrl+C to stop.

Device ID: 309265658
Model info: Unknown
Address: 192.168.178.54
Token: 4f5571477xxx via stored token
Support: Unknown
```

**Comment by afharo** [comment]
Googling around I found many applications that use UDP to struggle when running on Fritz! networks.

It looks like Fritz! has a special treatment for those packages. From previous comments, it _seems_ that it tries to optimize the routing of the packages, sending them to the place that responded to them.

If the routing table changes for any reason, Frizt! doesn't auto clean that routing optimization table, and sends the packages to a place where the robot is no longer listening to.

Can you look at the Fritz! configuration to figure out if there's anything UDP-related that can be tweaked?
