### ISSUE TITLE
Error on Homebridge

### ISSUE THREAD

**Issue by petrocino** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#455]
Hi there.

I got this error when I've tried to add to Homebridge:

```
[12/1/2021, 9:42:14 AM] [Xiaomi Mi Robot Vaccum-Mop P] INF getFirmware | viomi.vacuum.v8 | Firmwareversion is 3.5.3_0017
[12/1/2021, 9:42:17 AM] [homebridge-xiaomi-roborock-vacuum] This plugin slows down Homebridge. The read handler for the characteristic 'Serial Number' was slow to respond! See https://git.io/JtMGR for more info.
[12/1/2021, 9:42:23 AM] [homebridge-xiaomi-roborock-vacuum] This plugin slows down Homebridge. The read handler for the characteristic 'Serial Number' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[12/1/2021, 9:42:24 AM] [Xiaomi Mi Robot Vaccum-Mop P] ERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at module.exports.getSerialNumber (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/devices/viomivacuum.js:141:20)
    at XiaomiRoborockVacuum.getSerialNumber (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:842:28)
    at XiaomiRoborockVacuum.initializeDevice (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:690:24)
    at XiaomiRoborockVacuum.connect (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:770:7) {
  code: 'timeout'
}
[12/1/2021, 9:42:24 AM] [Xiaomi Mi Robot Vaccum-Mop P] STA getDevice | Serialnumber: Unknown
[12/1/2021, 9:42:24 AM] [Xiaomi Mi Robot Vaccum-Mop P] INF getFirmware | viomi.vacuum.v8 | Firmwareversion is 3.5.3_0017
[12/1/2021, 9:42:24 AM] [Xiaomi Mi Robot Vaccum-Mop P] STA getDevice | Firmwareversion: 3.5.3_0017
[12/1/2021, 9:42:24 AM] [Xiaomi Mi Robot Vaccum-Mop P] INF changedCleaning | viomi.vacuum.v8 | Cleaning is ON.
[12/1/2021, 9:42:24 AM] [Xiaomi Mi Robot Vaccum-Mop P] MON changedCharging | viomi.vacuum.v8 | ChargingState is now false
[12/1/2021, 9:42:24 AM] [Xiaomi Mi Robot Vaccum-Mop P] INF changedCharging | viomi.vacuum.v8 | Charging is cancelled
[12/1/2021, 9:42:24 AM] [Xiaomi Mi Robot Vaccum-Mop P] INF changedCharging | viomi.vacuum.v8 | Robot not anymore in dock.
[12/1/2021, 9:42:24 AM] [Xiaomi Mi Robot Vaccum-Mop P] MON changedSpeed | viomi.vacuum.v8 | FanSpeed is now 3%
[12/1/2021, 9:42:24 AM] [Xiaomi Mi Robot Vaccum-Mop P] INF changedSpeed | viomi.vacuum.v8 | Speed was changed to 3% (Turbo), for HomeKit 100%
[12/1/2021, 9:42:24 AM] [Xiaomi Mi Robot Vaccum-Mop P] INF changedPause | viomi.vacuum.v8 | Paused possible
[12/1/2021, 9:42:24 AM] [Xiaomi Mi Robot Vaccum-Mop P] ERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at module.exports.getSerialNumber (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/devices/viomivacuum.js:141:20)
    at XiaomiRoborockVacuum.getSerialNumber (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:842:28)
    at module.exports (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:20) {
  code: 'timeout'
}
```

It showed moments before, but now has vanished from home app, and presenting this error.
I've configured it as a 'bridge' into homebridge.

Any ideas??

**Comment by petrocino** [comment]
By the way:

My robot is the "Xiaomi Mi Robot Vacuum-Mop P"

**Comment by afharo** [comment]
Hi! Yeah... it's a known error for Viomi robots... I'll try to make this error silent while we figure out the right way to retrieve their serial number

**Comment by petrocino** [comment]
Right...
But two questions:

- It's normal, due this error, the plugin not work properly?
- It's correct to assign this plugins as a "bridge", to run isolated from all Homebridge system?

Tks
