### ISSUE TITLE
Mi Robot Vacuum-Mop 2 Pro (Not Support Problem)

### ISSUE THREAD

**Issue by fung199609** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#476]
Here's the basic information of my vacuum

NAME:     Mi Robot Vacuum-Mop 2 Pro
   ID:       1025342827
   MAC:      ec:4d:3e:e3:ec:e1
   IP:       xxx.xxx.xx.xx
   TOKEN:    xxxxxxxxxxxxxxxxxxxxxxxxxxxx
   MODEL:    ijai.vacuum.v3

And I'm not able to add this device to homekit.

The error log in homebridge:

[1/31/2022, 3:37:17 AM] [homebridge-xiaomi-roborock-vacuum] This plugin slows down Homebridge. The read handler for the characteristic 'Serial Number' was slow to respond! See https://git.io/JtMGR for more info.
[1/31/2022, 3:37:20 AM] [Xiaomi Mi Robot Vaccum 2 Pro] INF getCleaning | ijai.vacuum.v3 | Cleaning is false
[1/31/2022, 3:37:20 AM] [Xiaomi Mi Robot Vaccum 2 Pro] INF getCareSensors | ijai.vacuum.v3 | Sensors dirtytime is undefined seconds / NaN%.
[1/31/2022, 3:37:20 AM] [Xiaomi Mi Robot Vaccum 2 Pro] INF getCareFilter | ijai.vacuum.v3 | Filter worktime is undefined seconds / NaN%.
[1/31/2022, 3:37:20 AM] [Xiaomi Mi Robot Vaccum 2 Pro] INF getCareSideBrush | ijai.vacuum.v3 | Sidebrush worktime is undefined seconds / NaN%.
[1/31/2022, 3:37:20 AM] [Xiaomi Mi Robot Vaccum 2 Pro] INF getCareSensors | ijai.vacuum.v3 | Sensors dirtytime is undefined seconds / NaN%.
[1/31/2022, 3:37:20 AM] [Xiaomi Mi Robot Vaccum 2 Pro] INF getCareFilter | ijai.vacuum.v3 | Filter worktime is undefined seconds / NaN%.
[1/31/2022, 3:37:20 AM] [Xiaomi Mi Robot Vaccum 2 Pro] INF getCareSideBrush | ijai.vacuum.v3 | Sidebrush worktime is undefined seconds / NaN%.
[1/31/2022, 3:37:20 AM] [Xiaomi Mi Robot Vaccum 2 Pro] INF getCharging | ijai.vacuum.v3 | Charging is false (Status is undefined)
[1/31/2022, 3:37:20 AM] [Xiaomi Mi Robot Vaccum 2 Pro] INF getDocked | ijai.vacuum.v3 | Robot Docked is false (Status is undefined)
[1/31/2022, 3:37:20 AM] [Xiaomi Mi Robot Vaccum 2 Pro] INF getCareSensors | ijai.vacuum.v3 | Sensors dirtytime is undefined seconds / NaN%.
[1/31/2022, 3:37:20 AM] [Xiaomi Mi Robot Vaccum 2 Pro] INF getCareSensors | ijai.vacuum.v3 | Sensors dirtytime is undefined seconds / NaN%.
[1/31/2022, 3:37:20 AM] [Xiaomi Mi Robot Vaccum 2 Pro] INF getCareFilter | ijai.vacuum.v3 | Filter worktime is undefined seconds / NaN%.
[1/31/2022, 3:37:20 AM] [Xiaomi Mi Robot Vaccum 2 Pro] INF getCareFilter | ijai.vacuum.v3 | Filter worktime is undefined seconds / NaN%.
[1/31/2022, 3:37:20 AM] [Xiaomi Mi Robot Vaccum 2 Pro] INF getCareSideBrush | ijai.vacuum.v3 | Sidebrush worktime is undefined seconds / NaN%.
[1/31/2022, 3:37:20 AM] [Xiaomi Mi Robot Vaccum 2 Pro] INF getCareSideBrush | ijai.vacuum.v3 | Sidebrush worktime is undefined seconds / NaN%.
[1/31/2022, 3:37:20 AM] [Xiaomi Mi Robot Vaccum 2 Pro] INF getCareMainBrush | ijai.vacuum.v3 | Mainbrush worktime is undefined seconds / NaN%.
[1/31/2022, 3:37:20 AM] [Xiaomi Mi Robot Vaccum 2 Pro] INF getCareMainBrush | ijai.vacuum.v3 | Mainbrush worktime is undefined seconds / NaN%.
[1/31/2022, 3:37:20 AM] [Xiaomi Mi Robot Vaccum 2 Pro] INF getBatteryLow | ijai.vacuum.v3 | Batterylevel is -1%
[1/31/2022, 3:37:20 AM] [Xiaomi Mi Robot Vaccum 2 Pro] INF getBattery | ijai.vacuum.v3 | Batterylevel is -1%
[1/31/2022, 3:37:20 AM] [Xiaomi Mi Robot Vaccum 2 Pro] INF getSpeed | ijai.vacuum.v3 | Fanspeed is null over miIO. Converting to HomeKit
[1/31/2022, 3:37:20 AM] [homebridge-xiaomi-roborock-vacuum] This plugin generated a warning from the characteristic 'Battery Level': characteristic was supplied illegal value: number -1 exceeded minimum of 0. See https://git.io/JtMGR for more info.
[1/31/2022, 3:37:20 AM] [homebridge-xiaomi-roborock-vacuum] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[1/31/2022, 3:37:20 AM] [homebridge-xiaomi-roborock-vacuum] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[1/31/2022, 3:37:20 AM] [homebridge-xiaomi-roborock-vacuum] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[1/31/2022, 3:37:20 AM] [homebridge-xiaomi-roborock-vacuum] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[1/31/2022, 3:37:20 AM] [homebridge-xiaomi-roborock-vacuum] This plugin generated a warning from the characteristic 'Filter Life Level': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[1/31/2022, 3:37:21 AM] [Xiaomi Mi Robot Vaccum 2 Pro] INF getFirmware | ijai.vacuum.v3 | Firmwareversion is 4.3.3_0048
[1/31/2022, 3:37:23 AM] [homebridge-xiaomi-roborock-vacuum] This plugin slows down Homebridge. The read handler for the characteristic 'Serial Number' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[1/31/2022, 3:37:23 AM] [homebridge-xiaomi-roborock-vacuum] This plugin slows down Homebridge. The read handler for the characteristic 'Serial Number' was slow to respond! See https://git.io/JtMGR for more info.
[1/31/2022, 3:37:24 AM] [Xiaomi Mi Robot Vaccum 2 Pro] ERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at module.exports.getSerialNumber (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/devices/vacuum.js:189:20)
    at XiaomiRoborockVacuum.getSerialNumber (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:842:28)
    at module.exports (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/lib/callbackify.js:5:20) {
  code: 'timeout'
}

[1/31/2022, 3:39:35 AM] [Xiaomi Mi Robot Vaccum 2 Pro] ERR getRoomMap | Failed getting the Room Map. Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/device_info.js:227:12)
    at XiaomiRoborockVacuum.getRoomMap (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:1089:19)
    at XiaomiRoborockVacuum.initializeDevice (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:685:11)
    at XiaomiRoborockVacuum.connect (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/index.js:770:7) {
  code: 'timeout'
}
[1/31/2022, 3:39:35 AM] [Xiaomi Mi Robot Vaccum 2 Pro] ERR connect | miio.device, next try in 2 minutes | Error: Call to device timed out

All data is undefined and appear the getSerialNumber and getRoomMap error

**Comment by andychandowjones** [comment]
Any update?

**Comment by fung199609** [comment]
any update?
