### ISSUE TITLE
Room names not populated in the Home app on iOS 16

### ISSUE THREAD

**Issue by pawelaugustyn** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#557]
When I set up the room cleaning with Roborock S5, I get the following stack trace during my raspberry init. This happens **intermittently**, and sometimes these errors are not present during start up.

```
[19/09/2022, 12:27:16] [Odkurzacz] [Model=unknown] getSerialNumber | No vacuum cleaner is discovered yet.
[19/09/2022, 12:27:16] [Odkurzacz] [Model=unknown] getFirmware | No vacuum cleaner is discovered yet.
[19/09/2022, 12:27:16] [Odkurzacz] [Model=unknown] getCleaning | Failed getting the cleaning status. Error: Not connected yet
    at DeviceManager.get device [as device] (/var/lib/homebridge/node_modules/.pnpm/homebridge-xiaomi-roborock-vacuum@0.26.5/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/device_manager.ts:79:13)
    at DeviceManager.property (/var/lib/homebridge/node_modules/.pnpm/homebridge-xiaomi-roborock-vacuum@0.26.5/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/device_manager.ts:85:17)
    at MainService.get isCleaning [as isCleaning] (/var/lib/homebridge/node_modules/.pnpm/homebridge-xiaomi-roborock-vacuum@0.26.5/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/main_service.ts:115:39)
    at MainService.getCleaning (/var/lib/homebridge/node_modules/.pnpm/homebridge-xiaomi-roborock-vacuum@0.26.5/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/main_service.ts:121:31)
    at On.getHandler (/var/lib/homebridge/node_modules/.pnpm/homebridge-xiaomi-roborock-vacuum@0.26.5/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/main_service.ts:39:25)
    at On.<anonymous> (/var/lib/homebridge/node_modules/.pnpm/hap-nodejs@0.10.2/node_modules/hap-nodejs/src/lib/Characteristic.ts:1528:32)
    at step (/var/lib/homebridge/node_modules/.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js:144:27)
    at Object.next (/var/lib/homebridge/node_modules/.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js:125:57)
    at /var/lib/homebridge/node_modules/.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
[19/09/2022, 12:27:16] [Odkurzacz] [Model=unknown] getSpeed | No vacuum cleaner is discovered yet.
[19/09/2022, 12:27:16] [Odkurzacz] [Model=unknown] getCleaningRoom | No vacuum cleaner is discovered yet.
[19/09/2022, 12:27:16] [Odkurzacz] [Model=unknown] getCleaningRoom | No vacuum cleaner is discovered yet.
[19/09/2022, 12:27:16] [Odkurzacz] [Model=unknown] getCleaningRoom | No vacuum cleaner is discovered yet.
[19/09/2022, 12:27:16] [Odkurzacz] [Model=unknown] getCleaningRoom | No vacuum cleaner is discovered yet.
[19/09/2022, 12:27:16] [Odkurzacz] [Model=unknown] getCleaningRoom | No vacuum cleaner is discovered yet.
[19/09/2022, 12:27:16] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[19/09/2022, 12:27:16] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Status Low Battery': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[19/09/2022, 12:27:16] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Battery Level': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[19/09/2022, 12:27:16] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Charging State': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[19/09/2022, 12:27:16] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[19/09/2022, 12:27:16] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[19/09/2022, 12:27:16] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[19/09/2022, 12:27:16] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[19/09/2022, 12:27:16] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[19/09/2022, 12:27:16] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[19/09/2022, 12:27:16] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[19/09/2022, 12:27:16] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[19/09/2022, 12:27:16] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[19/09/2022, 12:27:16] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
```

I followed instructions from the [README section](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#semi-automatic), including setting a timer in the Mi Home app.

Accessory configuration:
```json
{
    "name": "Odkurzacz",
    "ip": "192.168.86.127",
    "token": "<<hidden>>",
    "waterBox": false,
    "dustCollection": false,
    "silent": true,
    "pause": false,
    "pauseWord": "pause",
    "findMe": false,
    "findMeWord": "where are you",
    "cleanword": "cleaning",
    "roomTimeout": 10,
    "autoroom": [
        "korytarz",
        "sypialnia",
        "biuro",
        "salon",
        "kuchnia"
    ],
    "accessory": "XiaomiRoborockVacuum"
}
```

In the Homebridge "Accessories" UI section, rooms are named correctly, but all switches in the Home app are called "Odkurzacz" (the name of the accessory from the config).

![IMG_C9D7B1A8C4EC-1](https://user-images.githubusercontent.com/26120235/191000280-9e363bef-b9f0-4daa-a9da-114abfe17ced.jpeg)

I use the plugin in `v0.26.5` version.

**Comment by okonet** [comment]
I'm experiencing the same issue on iOS 16 Home.app. Just installed latest update and it's still the case.

**Comment by pawelaugustyn** [comment]
O_o that's interesting. I checked the Home app on my iPad Air 2 (which won't get iPadOS 16) and the rooms are named properly. So I can confirm the issue is related to the Home app in iOS 16.
I'll update the issue name accordingly.

**Comment by okonet** [comment]
Thanks for the quick reply. Really appreciate it. And thanks for the link to the original issue. I was looking for it but could not found yet.
