### ISSUE TITLE
Error on finding hap-nodejs

### ISSUE THREAD

**Issue by sorriso93** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#558]
Hello starting from yesterday I get this error only on this plugin (I have 9 total plugin on my homebridge)

====================
[9/21/2022, 5:37:14 PM] ERROR LOADING PLUGIN homebridge-xiaomi-roborock-vacuum:
[9/21/2022, 5:37:14 PM] Error: Cannot find module 'hap-nodejs'
Require stack:
- /usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/dist/services/custom_care_service/care_service.js
- /usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/dist/services/custom_care_service/index.js
- /usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/dist/services/care_service.js
- /usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/dist/services/index.js
- /usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/dist/xiaomi_roborock_vacuum_accessory.js
- /usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at Function.Module._load (node:internal/modules/cjs/loader:763:27)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/custom_care_service/care_service.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
[9/21/2022, 5:37:14 PM] ====================

I didn't make any change, also tried to update to last version with no success, same error.
Any idea? 
I already tried to put a symbolic link of the file in the plugin folder as suggested with a quick search on google...
M

PS: hap-nodejs is installed and I didn't change anything on configuration in last days, the path is and was the same >> ./usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs

**Comment by afharo** [comment]
Hi @sorriso93,

what is the version of `homebridge` and `hap-nodejs` that you've got installed? I'm trying to figure out what might be wrong here

**Comment by sorriso93** [comment]
Hello, homebridge v1.5.0 , node.js v 15.3. I don't know how to see hap-node.js version, googled it with no success...

**Comment by sorriso93** [comment]
Also in addition with iOS6 the room names don't appear anymore... I don't know if it is correlated...

my json, was good till iOS16

   {
            "name": "Aspirapolvere",
            "ip": "192.168.0.17",
            "token": "xxxxx",
            "waterBox": true,
            "silent": false,
            "pause": false,
            "pauseWord": "pausa",
            "findMe": false,
            "findMeWord": "dove sei",
            "dock": true,
            "cleanword": "Pulisci",
            "roomTimeout": 3,
            "autoroom": false,
            "rooms": [
                {
                    "name": "Camera Fede",
                    "id": 16
                },
                {
                    "name": "Bagno Fede",
                    "id": 17
                },
                {
                    "name": "Bagno Max",
                    "id": 18
                },
                {
                    "name": "Sala",
                    "id": 19
                },
                {
                    "name": "Camera",
                    "id": 20
                },
                {
                    "name": "Cucina",
                    "id": 21
                }
            ],
            "accessory": "XiaomiRoborockVacuum",
            "_bridge": {
                "username": "xxxx",
                "port": 59000
            }
        },

**Comment by afharo** [comment]
@sorriso93 From your last comment, I assume the error is not present anymore and the plugin is working?

Regarding the names, it's a bug in iOS16. More info (and the workaround) in this issue: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/issues/552

**Comment by sorriso93** [comment]
I still have the problem of error on hap-nodejs

**Comment by afharo** [comment]
So the plugin doesn't crash. It only logs the error?

**Comment by sorriso93** [comment]
the accessories are not responding on home app, therefore I cannot use it. 
The plugin doesn't load from the log below (please note I have it in child-bridge configuration)

[9/26/2022, 1:17:08 AM] ---
[9/26/2022, 1:17:09 AM] ====================
[9/26/2022, 1:17:09 AM] ERROR LOADING PLUGIN homebridge-xiaomi-roborock-vacuum:
[9/26/2022, 1:17:09 AM] Error: Cannot find module 'hap-nodejs'
Require stack:
- /usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/dist/services/custom_care_service/care_service.js
- /usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/dist/services/custom_care_service/index.js
- /usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/dist/services/care_service.js
- /usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/dist/services/index.js
- /usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/dist/xiaomi_roborock_vacuum_accessory.js
- /usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/dist/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:15)
    at Function.Module._load (node:internal/modules/cjs/loader:763:27)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/custom_care_service/care_service.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
[9/26/2022, 1:17:09 AM] ====================
[9/26/2022, 1:17:09 AM] Loading 4 platforms...
[9/26/2022, 1:17:09 AM] [Harmony] Initializing HarmonyHubWebSocket platform...
[9/26/2022, 1:17:09 AM] [Harmony] Initializing child bridge 0E:B5:5E:27:9E:C3
[9/26/2022, 1:17:09 AM] [Netatmo] Initializing netatmo platform...
[9/26/2022, 1:17:09 AM] [Netatmo] Initializing child bridge 0E:29:F2:D5:BD:2E
[9/26/2022, 1:17:09 AM] [Camera-IP] Initializing Camera-IP platform...
[9/26/2022, 1:17:09 AM] [Camera-IP] Initializing child bridge 0E:C4:2D:C0:5A:D9
[9/26/2022, 1:17:09 AM] Loading 9 accessories...
[9/26/2022, 1:17:09 AM] No plugin was found for the accessory "XiaomiRoborockVacuum" in your config.json. Please make sure the corresponding plugin is installed correctly.
[9/26/2022, 1:17:09 AM] [Whithings] Initializing Withings Air Quality accessory...
[9/26/2022, 1:17:09 AM] [APPLE LAMP] Initializing HttpPushRgb accessory...
[9/26/2022, 1:17:09 AM] [APPLE LAMP] Initializing child bridge 0E:56:FA:3A:24:3B
[9/26/2022, 1:17:09 AM] [Orologio] Initializing HTTP-SWITCH accessory...
[9/26/2022, 1:17:09 AM] [Orologio] Initializing child bridge 0E:42:2E:3D:6A:F2
[9/26/2022, 1:17:09 AM] [Orologio Reset] Initializing HTTP-SWITCH accessory...
[9/26/2022, 1:17:09 AM] [Orologio Reset] Initializing child bridge 0E:E3:4F:46:CA:A8
[9/26/2022, 1:17:09 AM] [Clock arcade] Initializing HTTP-SWITCH accessory...
[9/26/2022, 1:17:09 AM] [Clock arcade] Initializing child bridge 0E:96:E3:27:72:ED
[9/26/2022, 1:17:09 AM] [Cambia quadro] Initializing HTTP-SWITCH accessory...
[9/26/2022, 1:17:09 AM] [Cambia quadro] Initializing child bridge 0E:9C:1D:75:9B:6B
[9/26/2022, 1:17:09 AM] [Bandwidth M] Initializing HTTP-SWITCH accessory...
[9/26/2022, 1:17:09 AM] [Bandwidth M] Initializing child bridge 0E:49:6E:6D:9F:8C
[9/26/2022, 1:17:09 AM] [Bandwidth F] Initializing HTTP-SWITCH accessory...
[9/26/2022, 1:17:09 AM] [Bandwidth F] Initializing child bridge 0E:35:48:9B:E4:F9
Setup Payload:
X-HM://0023NPVXYWYXI
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:

**Comment by sorriso93** [comment]
and this is the config part

 "accessories": [
        {
            "name": "Aspirapolvere",
            "ip": "192.168.0.17",
            "token": "7750794d5033354b6b494a34536b4870",
            "waterBox": true,
            "silent": false,
            "pause": false,
            "pauseWord": "pausa",
            "findMe": false,
            "findMeWord": "dove sei",
            "dock": true,
            "cleanword": "Pulisci",
            "roomTimeout": 3,
            "autoroom": false,
            "rooms": [
                {
                    "name": "Camera Fede",
                    "id": 16
                },
                {
                    "name": "Bagno Fede",
                    "id": 17
                },
                {
                    "name": "Bagno Max",
                    "id": 18
                },
                {
                    "name": "Sala",
                    "id": 19
                },
                {
                    "name": "Camera",
                    "id": 20
                },
                {
                    "name": "Cucina",
                    "id": 21
                }
            ],
            "accessory": "XiaomiRoborockVacuum",
            "_bridge": {
                "username": "0E:84:1F:E8:89:52",
                "port": 59000
            }
        },

**Comment by sorriso93** [comment]
Hello with the symlink no way to have it functional whereas installing locally seems ok, I get in the log the following alert:

[9/27/2022, 12:54:24 PM] The plugin "homebridge-xiaomi-roborock-vacuum" defines 'homebridge' and/or 'hap-nodejs' in their 'dependencies' section, meaning they carry an additional copy of homebridge and hap-nodejs. This not only wastes disk space, but also can cause major incompatibility issues and thus is considered bad practice. Please inform the developer to update their plugin!

**Comment by afharo** [comment]
Thanks! FWIW, I moved the dependency to the peerDependency to avoid that same warning and it seemed to work for most folks.

Apparently it's not working for some others... 

I'll see how I can remove that dependency once and for all.

**Comment by afharo** [comment]
Can you confirm https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.27.0 fixed these issues, please?

**Comment by sorriso93** [comment]
Ciao I don't see any warning on the homebridge log right now and seems good the plugin behaviour. Many thanks
