### ISSUE TITLE
HomeBridge roborock s6 log errors after update to latest plugin version

### ISSUE THREAD

**Issue by nseries100** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#583]
It worked fine some time. Today I want to update some plugins and when I was checking log I found these errors for my roborock s6 after update to latest plugin version. Settings did not changed.

For now Im back on this version homebridge-xiaomi-roborock-vacuum v0.26.3 and it looks like its working again.

`[16/10/2022, 14:31:22] [Vysavač] [Model=unknown] getSerialNumber | No vacuum cleaner is discovered yet.
[16/10/2022, 14:31:22] [Vysavač] [Model=unknown] getFirmware | No vacuum cleaner is discovered yet.
[16/10/2022, 14:31:22] [Vysavač] [Model=unknown] getCleaning | Failed getting the cleaning status. Error: Not connected yet
    at DeviceManager.get device [as device] (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/device_manager.ts:79:13)
    at DeviceManager.property (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/device_manager.ts:85:17)
    at DeviceManager.get state [as state] (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/device_manager.ts:66:17)
    at DeviceManager.get isCleaning [as isCleaning] (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/device_manager.ts:70:43)
    at MainService.getCleaning (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/main_service.ts:108:45)
    at On.getHandler (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/main_service.ts:38:25)
    at On.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1528:32)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
[16/10/2022, 14:31:22] [Vysavač] [Model=unknown] getSpeed | No vacuum cleaner is discovered yet.
[16/10/2022, 14:31:22] [Phoscon deConz] Philips Hue Go: set homekit supported transition configuration to {"configuration":[{"iid":11,"characteristic":1},{"iid":13,"characteristic":2}]}
[16/10/2022, 14:31:22] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[16/10/2022, 14:31:22] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Status Low Battery': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[16/10/2022, 14:31:22] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Battery Level': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[16/10/2022, 14:31:22] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Charging State': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[16/10/2022, 14:31:22] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[16/10/2022, 14:31:22] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[16/10/2022, 14:31:22] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[16/10/2022, 14:31:22] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[16/10/2022, 14:31:22] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[16/10/2022, 14:31:22] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[16/10/2022, 14:31:22] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[16/10/2022, 14:31:22] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[16/10/2022, 14:31:23] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[16/10/2022, 14:31:23] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.`

**Comment by afharo** [comment]
@nseries100 those logs show that the plugin did not manage to connect to the vacuum yet. But it keeps trying. The same applies to older versions.

Did you get any sort of crash or anything that made you roll back to the previous version?

**Comment by nseries100** [comment]
I rolled back to older version because I want to try if it will be work again. And It just works. Older version = no errors in log.

**Comment by dehlen** [comment]
I am having the same problem. It worked when initially setup but now does not. I have a static IP for my roborock s6 and the token is definitely correct. Rolling back to 0.26.3 did not work for me.

**Comment by afharo** [comment]
FWIW, the reconnection logic has not changed in recent versions.

The described behavior seems familiar as it has randomly happened in the past. The plugin failed to connect on the first attempt and was not able to connect on the retries. Typically, restarting the plugin (sometimes a couple of times would fix it).

Probably that's why @nseries100 saw this resolved after rolling back. But @dehlen's scenario confirms it's not a regression of the latest version.

@nseries100 would you mind trying to upgrade again and confirm if you still see that issue?
