### ISSUE TITLE
no connection possible - token and ip works

### ISSUE THREAD

**Issue by Grobi4476** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#626]
Mehrere Male probiert, leider komme ich nicht weiter... 

```
19.12.2022, 00:02:16Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationINF ensureDevice | dreame.vacuum.p2009 | The socket was destroyed or not initialised, initialising the device
19.12.2022, 00:02:28Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationSTA getDevice | Connected to: 192.168.1.216
19.12.2022, 00:02:28Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationSTA getDevice | Model: dreame.vacuum.p2009
19.12.2022, 00:02:28Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationSTA getDevice | State: undefined
19.12.2022, 00:02:28Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationSTA getDevice | FanSpeed: undefined
19.12.2022, 00:02:28Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationSTA getDevice | BatteryLevel: undefined
19.12.2022, 00:02:40Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationWARNUNGERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/var/lib/hoobs/huebridge/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/network.js:519:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 'timeout'
}
19.12.2022, 00:02:40Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationSTA getDevice | Serialnumber: Unknown
19.12.2022, 00:02:40Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationINF getFirmware | dreame.vacuum.p2009 | Firmwareversion is 4.1.8_1132
19.12.2022, 00:02:40Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationSTA getDevice | Firmwareversion: 4.1.8_1132
19.12.2022, 00:02:52Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationFEHLERERR getState | {"code":"timeout"}
19.12.2022, 00:02:58Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationFEHLERERR getState | {"code":"timeout"}
19.12.2022, 00:03:04Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationFEHLERERR getState | {"code":"timeout"}
19.12.2022, 00:03:34Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationFEHLERERR getState | {"code":"timeout"}
19.12.2022, 00:04:04Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationFEHLERERR getState | {"code":"timeout"}
19.12.2022, 00:04:34Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationFEHLERERR getState | {"code":"timeout"}
19.12.2022, 00:05:04Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationFEHLERERR getState | {"code":"timeout"}
19.12.2022, 00:05:34Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationFEHLERERR getState | {"code":"timeout"}
19.12.2022, 00:06:04Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationFEHLERERR getState | {"code":"timeout"}
19.12.2022, 00:06:34Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationFEHLERERR getState | {"code":"timeout"}
19.12.2022, 00:06:58Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationFEHLERERR getState | {}
19.12.2022, 00:07:22Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationINF ensureDevice | dreame.vacuum.p2009 | The socket was destroyed or not initialised, initialising the device
19.12.2022, 00:07:34Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationSTA getDevice | Connected to: 192.168.1.216
19.12.2022, 00:07:34Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationSTA getDevice | Model: dreame.vacuum.p2009
19.12.2022, 00:07:34Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationSTA getDevice | State: undefined
19.12.2022, 00:07:34Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationSTA getDevice | FanSpeed: undefined
19.12.2022, 00:07:34Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationSTA getDevice | BatteryLevel: undefined
19.12.2022, 00:07:46Hue BridgeXiaomi Mi Robot Vaccum 1st GenerationWARNUNGERR getSerialNumber | Failed getting the serial number. Error: Call to device timed out
    at Timeout.retry [as _onTimeout] (/var/lib/hoobs/huebridge/node_modules/homebridge-xiaomi-roborock-vacuum/miio/lib/network.js:519:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 'timeout'
}
```

**Comment by afharo** [comment]
Hi @Grobi4476, from the logs, I gather your device is one of the Dreame series: `Model: dreame.vacuum.p2009`

Unfortunately, this device is not supported yet (refer to #407).

Xiaomi doesn't help much because every brand (Roborock, Dreame, Viomi, ...) has a different set of commands (why would they use the same, right?).

If you don't mind, I'll close this issue and we can follow up on the discussion on #407

**Comment by Grobi4476** [comment]
Hi @afharo, yes that's right, thanks for the support. Do you know when it will be supported or there no plans to do it?

**Comment by afharo** [comment]
I'm always looking to onboard new models. However, it's not an easy task... the documentation is never very clear, and sometimes getting to feature parity is almost impossible... 

I only own a Roborock S5, so I cannot test my own.

As Xiaomi is branching into more and more brands, I'm planning to add a guide for owners to test and discover the commands, and a template for them to follow to submit a PR to this plugin.

However, life gets on the way with the many plans I've got for this plugin. If you feel like trying to submit the PR yourself, I'm happy to provide guidance :)
