### ISSUE TITLE
cannot find vaccum

### ISSUE THREAD

**Issue by sonikot** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#639]
Hello,

I am having an issue with the homebridge unable to find the vacuum i have setup everything correct, any ideas why it won't discover the vacuum?

[2023-01-10, 9:54:48 p.m.] [Robo] [Model=unknown] getSerialNumber | No vacuum cleaner is discovered yet.
[2023-01-10, 9:54:48 p.m.] [Robo] [Model=unknown] INF ensureDevice | unknown model | The socket was destroyed or not initialised, initialising the device
[2023-01-10, 9:54:48 p.m.] [Robo] [Model=unknown] getFirmware | No vacuum cleaner is discovered yet.
[2023-01-10, 9:54:48 p.m.] [Robo] [Model=unknown] INF ensureDevice | unknown model | The socket was destroyed or not initialised, initialising the device
[2023-01-10, 9:54:48 p.m.] [Robo] [Model=unknown] getCleaning | Failed getting the cleaning status. Error: Not connected yet
    at DeviceManager.get device [as device] (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/device_manager.ts:86:13)
    at DeviceManager.property (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/device_manager.ts:92:17)
    at DeviceManager.get state [as state] (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/device_manager.ts:73:17)
    at DeviceManager.get isCleaning [as isCleaning] (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/device_manager.ts:77:43)
    at MainService.getCleaning (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/main_service.ts:108:45)
    at On.getHandler (/usr/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/main_service.ts:38:25)
    at On.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2399:32)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
[2023-01-10, 9:54:48 p.m.] [Robo] [Model=unknown] getSpeed | No vacuum cleaner is discovered yet.
[2023-01-10, 9:54:48 p.m.] [Robo] [Model=unknown] INF ensureDevice | unknown model | The socket was destroyed or not initialised, initialising the device

**Comment by nail299** [comment]
Same here:
Homebridge v18.12.1 (Syno Docker, 'Homebridge Fritz Platform' as the only other plugin working fine)
homebridge-xiaomi-roborock-vacuum v0.28.1
Model: rockrobo.vacuum.v1 (FW 3.3.9_003502, itself working via seamlessly Xiaomi Home app (iOS)
Token and IP double-checked and correct

```
[1/12/2023, 7:44:31 PM] [Xiaomi Mi Robot] [Model=unknown] getSpeed | No vacuum cleaner is discovered yet.
[1/12/2023, 7:44:31 PM] [Xiaomi Mi Robot] [Model=unknown] INF ensureDevice | unknown model | The socket was destroyed or not initialised, initialising the device
[1/12/2023, 7:44:31 PM] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[1/12/2023, 7:44:31 PM] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[1/12/2023, 7:44:31 PM] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[1/12/2023, 7:44:31 PM] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Status Low Battery': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[1/12/2023, 7:44:31 PM] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Battery Level': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[1/12/2023, 7:44:31 PM] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Charging State': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[1/12/2023, 7:44:31 PM] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Occupancy Detected': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[1/12/2023, 7:44:31 PM] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[1/12/2023, 7:44:31 PM] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[1/12/2023, 7:44:31 PM] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[1/12/2023, 7:44:31 PM] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[1/12/2023, 7:44:31 PM] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[1/12/2023, 7:44:31 PM] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[1/12/2023, 7:44:31 PM] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Change Indication': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[1/12/2023, 7:44:31 PM] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Filter Life Level': Unhandled error thrown inside read handler for characteristic: Not connected yet. See https://homebridge.io/w/JtMGR for more info.
[1/12/2023, 7:44:33 PM] [Xiaomi Mi Robot] [Model=unknown] ERR connect | miio.device, next try in 2 minutes | Error: Could not connect to device, handshake timeout
[1/12/2023, 7:44:33 PM] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Rotation Speed': Unhandled error thrown inside read handler for characteristic: Could not connect to device, handshake timeout. See https://homebridge.io/w/JtMGR for more info.

```

**Comment by afharo** [comment]
@nail299 from your comment... am I right to assume you use a fritz! router?

For some reason, they are very picky with UDP packets and filter treat them in a way that breaks this plugin (that uses UDP to communicate with the router).

Can you look into the configuration of your router to see if there's a way to allow those UDP packets to flow in your network?

**Comment by afharo** [comment]
For the Fritz routers, please refer to #444. I'll go ahead and close this one as duplicate.
