### ISSUE TITLE
Xiaomi vacuum mop 2

### ISSUE THREAD

**Issue by AleDon88** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#667]
Hi, 
a Xiaomi Vacuum Mop 2 doesn't work, following the error that I get when I try to use it: 
```
[01/03/2023, 08:36:44] [homebridge-xiaomi-roborock-vacuum] This plugin threw an error from the characteristic 'Rotation Speed': Unhandled error thrown inside write handler for characteristic: Call to device timed out. See https://homebridge.io/w/JtMGR for more info.
[01/03/2023, 08:36:44] [Xiaomi] [Model=dreame.vacuum.p2140p] setCleaning | Failed to set cleaning to true Error: Call to device timed out
    at DeviceInfo._retryOnTimeout (/var/lib/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/miio/lib/device_info.js:295:29)
    at DeviceInfo.call (/var/lib/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/miio/lib/device_info.js:227:12)
    at MainService.setCleaning (/var/lib/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/main_service.ts:135:11) {
  code: 'timeout'
```

This is the error that I see in the logs during the installation of plugin: 

`[28/02/2023, 22:09:07] [homebridge-xiaomi-roborock-vacuum] This plugin slows down Homebridge. The read handler for the characteristic 'Serial Number' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.`

The vacuum cleaner has a static IP.

Thanks

**Comment by afharo** [comment]
> [Model=dreame.vacuum.p2140p]

Unfortunately, the Dreame series is not supported yet... It requires a totally different set of commands and needs it's own implementation. Any PRs to add support to that line is very welcomed 😇
