### ISSUE TITLE
iOS 17 - grouped switches in single tile without names

### ISSUE THREAD

**Issue by maisun** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#800]
Hi,
Would like to report an issue after upgrading to iOS 17, just to be clear it is not something to do with the add-on but would like to bring some discussion on potential workaround.
After upgrading to iOS 17 the grouped items in single tile lose name description, it is particularly an issue if you have switches for many rooms and would like to start cleaning only certain rooms. Now those switches don't have a name/description in iOS 17.
In earlier version there was the workaround to rename the accessory but this workaround doesn't work in iOS 17 looks like. 
I'm think as potential workaround maybe the add-on can allow user to define a list of rooms with one switch with the attempt to reduce the number of switches. Any thoughts or please share if you have another workaround? Many thanks!

**Comment by afharo** [comment]
> I think as potential workaround maybe the add-on can allow user to define a list of rooms with one switch with the attempt to reduce the number of switches.

Just to make sure I understood: 
* Do you mean exposing a switch that would trigger the cleaning of a few rooms?
* Or are you suggesting a selector (like the image below) where you have an ON/OFF button and a selector of which room to clean?
![image](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/assets/5469006/fb0a9924-1963-4f33-b77f-27eb01c79670)

**Comment by maisun** [comment]
BTW the TV accessory sounds interesting however you cannot control the power as a fan.
One solution could be to use TV remote and volume control for fan speed, and in the remote it also has up, down, left, right button for remote control the cleaner, that could be fun idea :)

**Comment by afharo** [comment]
I'm wondering: if we find a way to "independent" accessories so that we can place each room's button in their own room, would it solve this issue?

**Comment by maisun** [comment]
> I'm wondering: if we find a way to "independent" accessories so that we can place each room's button in their own room, would it solve this issue?

We can already do that now I think (to some extend). In my use-case I usually clean multiple rooms and hence less convenient to find the rooms and turn on the clean switch (I have hundreds of HK accessories). 
Another option is to simply create a room for the cleaner so all switches are in the same place (I'm using this workaround now).

**Comment by T-Bone90** [comment]
I have the same problem with iOS 17.
Is there any fix for this?

![Uploading IMG_3877.PNG…]()

**Comment by T-Bone90** [comment]
I have the same problem with iOS 17.
Is there any fix for this?
![IMG_3877](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/assets/62621395/2c73470d-2b35-4ec8-86d2-7c4fbccda662)

**Comment by maisun** [comment]
Think it's a change by Apple don't think there is a fix unfortunately

**Comment by tasict** [comment]
@maisun 
    After iOS 16, the display in this area has been adjusted, and it is required to set the switch names to be displayed in the following manner.

    addOptionalCharacteristic(this.platform.Characteristic.ConfiguredName);
    setCharacteristic(this.platform.Characteristic.ConfiguredName, buttonNanoName);
    
    If needed, I can submit a pull request to assist with the modification.

**Comment by maisun** [comment]
> @afharo @maisun After iOS 16, the display in this area has been adjusted, and it is required to set the switch names to be displayed in the following manner.
> 
> ```
> addOptionalCharacteristic(this.platform.Characteristic.ConfiguredName);
> setCharacteristic(this.platform.Characteristic.ConfiguredName, buttonNanoName);
> 
> If needed, I can submit a pull request to assist with the modification.
> ```

Yes please, it’s not very usable without name, very much appreciated!

**Comment by tasict** [comment]
> > @afharo @maisun After iOS 16, the display in this area has been adjusted, and it is required to set the switch names to be displayed in the following manner.
> > ```
> > addOptionalCharacteristic(this.platform.Characteristic.ConfiguredName);
> > setCharacteristic(this.platform.Characteristic.ConfiguredName, buttonNanoName);
> > 
> > If needed, I can submit a pull request to assist with the modification.
> > ```
> 
> Yes please, it’s not very usable without name, very much appreciated!

Done
https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/pull/889

**Comment by maisun** [comment]
> > > @afharo @maisun After iOS 16, the display in this area has been adjusted, and it is required to set the switch names to be displayed in the following manner.
> > > ```
> > > addOptionalCharacteristic(this.platform.Characteristic.ConfiguredName);
> > > setCharacteristic(this.platform.Characteristic.ConfiguredName, buttonNanoName);
> > > 
> > > If needed, I can submit a pull request to assist with the modification.
> > > ```
> > 
> > 
> > Yes please, it’s not very usable without name, very much appreciated!
> 
> Done #889

Great, 

> > > @afharo @maisun After iOS 16, the display in this area has been adjusted, and it is required to set the switch names to be displayed in the following manner.
> > > ```
> > > addOptionalCharacteristic(this.platform.Characteristic.ConfiguredName);
> > > setCharacteristic(this.platform.Characteristic.ConfiguredName, buttonNanoName);
> > > 
> > > If needed, I can submit a pull request to assist with the modification.
> > > ```
> > 
> > 
> > Yes please, it’s not very usable without name, very much appreciated!
> 
> Done #889

Thank you! I just gave a try but got the below error, not sure what caused it:
[3/6/2024, 1:26:12 PM] Loaded 0 cached accessories from cachedAccessories.0EBD4D23CE69.
TypeError: Cannot read properties of undefined (reading 'platform')
    at ensureName (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/utils/ensure_name.ts:18:2)
    at RoomsService.createRoom (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/rooms_service.ts:88:15)
    at new RoomsService (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/rooms_service.ts:35:14)
    at XiaomiRoborockVacuum.initializeServices (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/xiaomi_roborock_vacuum_accessory.ts:94:19)
    at new XiaomiRoborockVacuum (/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/xiaomi_roborock_vacuum_accessory.ts:80:32)
    at ChildBridgeFork.startBridge (/homebridge/node_modules/homebridge/src/childBridgeFork.ts:172:52)

**Comment by tasict** [comment]
I’ll fixed it later.

**Comment by afharo** [comment]
>    @afharo  @maisun 
> 
>     After iOS 16, the display in this area has been adjusted, and it is required to set the switch names to be displayed in the following manner.
> 
> 
> 
>     addOptionalCharacteristic(this.platform.Characteristic.ConfiguredName);
> 
>     setCharacteristic(this.platform.Characteristic.ConfiguredName, buttonNanoName);
> 
>     
> 
>     If needed, I can submit a pull request to assist with the modification.

@tasict, AFAIK, those changes were introduced in 0.31.1.
Did I misunderstand your proposal?

**Comment by tasict** [comment]
@afharo In fact, upon closer review of your code, I found that there isn't much difference in logic between my code and yours. However, surprisingly, the plugin I wrote does not experience any text disappearance issues on the Home App.

https://github.com/tasict/homebridge-panasonic-smart-app/blob/ed1c3cd122a51f58b58e53e8ad1ad2625bb091b6/src/accessories/dehumidifier.ts#L178

![IMG_6032](https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/assets/9862066/ae2a3934-9c71-41c4-9b8d-5c5d29297963)

**Comment by maisun** [comment]
> @afharo In fact, upon closer review of your code, I found that there isn't much difference in logic between my code and yours. However, surprisingly, the plugin I wrote does not experience any text disappearance issues on the Home App.
> 
> https://github.com/tasict/homebridge-panasonic-smart-app/blob/ed1c3cd122a51f58b58e53e8ad1ad2625bb091b6/src/accessories/dehumidifier.ts#L178
> 
> ![IMG_6032](https://private-user-images.githubusercontent.com/9862066/311139852-ae2a3934-9c71-41c4-9b8d-5c5d29297963.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODAyNDksIm5iZiI6MTcwOTg3OTk0OSwicGF0aCI6Ii85ODYyMDY2LzMxMTEzOTg1Mi1hZTJhMzkzNC05YzcxLTQxYzQtOWI4ZC01YzVkMjkyOTc5NjMuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDhUMDYzOTA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWM1NTRmZTdlMWJlZDViNzRkMjM1MjAzMjIyMjJiNTI2MWVkMTZlZDU1OTQ1OWQwZDk2MTczYjFiNDIxYjc0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pn1gBdVz9ptxL4ehmqTa1qBdfkO2c21aVtCJANjR-GI)

Hi, are you on iOS 17? I started to have this problem with iOS 17, it worked fine with iOS 16 before upgrade.

**Comment by tasict** [comment]
@maisun Yes, it's iOS 17.4

**Comment by afharo** [comment]
@tasict, maybe the difference is that this plugin only calls the setter if a custom name is specified.

I'll try to change that logic to always call it on init

**Comment by maisun** [comment]
Any update on this? Do we know if it's a HomeKit (Home App) issue or something we can change in the plugin? It is a bit strange that before iOS 17 everything worked fine.

**Comment by afharo** [comment]
Sorry! I was fixing it as part of https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/pull/855 and life got in the way... I need to finish that PR :)

**Comment by maisun** [comment]
> Sorry! I was fixing it as part of #855 and life got in the way... I need to finish that PR :)

Hi sorry to ask but just want to know if there is any hope but looks like it's on the way, appreciate your effort :)
