### ISSUE TITLE
Homebridge v2.0 Breaking Updates

### ISSUE THREAD

**Issue by mitch7391** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#958]
**Please describe the problem:**

I am not sure if you are aware but the next version of Homebridge (v2.0) comes with breaking changes for a lot of Homebridge plug-ins and it has been put on the developers to update their plug-ins.

[For Plug-In Developers](https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2#for-plugin-developers)

I have tested this plug-in on the beta version and it will crash Homebridge.

**Describe the solution you'd like:**
Please have a read of the link above and see what changes are required for this plug-in.

**Describe alternatives you've considered:**
All users of this plug-in will have to remain on Homebridge v1.8.4.

**Additional context:**
![image](https://github.com/user-attachments/assets/c82eeea1-16a4-400b-aefa-c13dfec35d1d)

**Comment by afharo** [comment]
Thank you for the heads up! May I know when is v2.0 expected to be released?

**Comment by mitch7391** [comment]
@afharo no worries :) also I am not sure what their timeline is sorry!

**Comment by mitch7391** [comment]
Adding logs just in case :)

```
[27/07/2024, 3:19:31 pm] [Roborock] Restarting Process...
[27/07/2024, 3:19:33 pm] [Roborock] Launched child bridge with PID 17443
[27/07/2024, 3:19:33 pm] Registering accessory 'homebridge-xiaomi-roborock-vacuum.XiaomiRoborockVacuum'
[27/07/2024, 3:19:33 pm] [Roborock] Loaded homebridge-xiaomi-roborock-vacuum v0.31.1 child bridge successfully
[27/07/2024, 3:19:33 pm] Loaded 0 cached accessories from cachedAccessories.0E8A2B113731.
TypeError: this.hap.Service.BatteryService is not a constructor
    at new BatteryInfo (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/battery_info.ts:11:20)
    at XiaomiRoborockVacuum.initializeServices (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/xiaomi_roborock_vacuum_accessory.ts:111:16)
    at new XiaomiRoborockVacuum (/usr/local/lib/node_modules/homebridge-xiaomi-roborock-vacuum/src/xiaomi_roborock_vacuum_accessory.ts:80:32)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:177:52)
[27/07/2024, 3:19:34 pm] [Roborock] Child bridge process ended
[27/07/2024, 3:19:34 pm] [Roborock] Process Ended. Code: 1, Signal: null
```

**Comment by bwp91** [comment]
`this.hap.Service.BatteryService` -> `this.hap.Service.Battery`

**Comment by afharo** [comment]
WIP: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/pull/960

**Comment by dcompane** [comment]
Sorry for reopening. If the fix is in the current release, can you mark as verified for 2.0?

<img width="853" alt="image" src="https://github.com/user-attachments/assets/29ededf7-7574-47ae-8a71-4da51310c57e">

**Comment by mitch7391** [comment]
@afharo all you will need to do is the [following](https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0#homebridge-v2).

**Comment by afharo** [comment]
Oh! Sorry! I'll submit a new version  with the fixes today

**Comment by afharo** [comment]
Apologies for the delay: https://github.com/homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum/releases/tag/v0.32.1 should include the required changes.
