### ISSUE TITLE
Still S6 not found

### ISSUE THREAD

**Issue by panthertom** [homebridge-xiaomi-roborock-vacuum/homebridge-xiaomi-roborock-vacuum#975]
Dear afharo,
sorry for bothering you with this issue again:
I tried to connect my S6 again as it is connected to a new router.

As already mentioned this is the log file:
Logfile
[9/1/2024, 10:17:09 PM] [Xiaomi Mi Robot Vaccum 1st Generation Neu] [Model=unknown] getSerialNumber | No vacuum cleaner is discovered yet.
[9/1/2024, 10:17:09 PM] [Xiaomi Mi Robot Vaccum 1st Generation Neu] [Model=unknown] INF ensureDevice | unknown model | The socket was destroyed or not initialised, initialising the device
[9/1/2024, 10:17:09 PM] [Xiaomi Mi Robot Vaccum 1st Generation Neu] [Model=unknown] getFirmware | No vacuum cleaner is discovered yet.
[9/1/2024, 10:17:09 PM] [Xiaomi Mi Robot Vaccum 1st Generation Neu] [Model=unknown] INF ensureDevice | unknown model | The socket was destroyed or not initialised, initialising the device
[9/1/2024, 10:17:09 PM] [Xiaomi Mi Robot Vaccum 1st Generation Neu] [Model=unknown] getCleaning | Failed getting the cleaning status. Error: Not connected yet
    at DeviceManager.get device [as device] (/volume1/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/device_manager.ts:86:13)
    at DeviceManager.property (/volume1/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/device_manager.ts:92:17)
    at DeviceManager.get state [as state] (/volume1/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/device_manager.ts:73:17)
    at DeviceManager.get isCleaning [as isCleaning] (/volume1/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/device_manager.ts:77:43)
    at MainService.getCleaning (/volume1/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/main_service.ts:115:45)
    at On.getHandler (/volume1/homebridge/node_modules/homebridge-xiaomi-roborock-vacuum/src/services/main_service.ts:45:25)
    at On.<anonymous> (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2404:32)
    at step (/volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:195:27)
    at Object.next (/volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:176:57)
    at /volume1/homebridge/node_modules/homebridge/node_modules/tslib/tslib.js:169:75
[9/1/2024, 10:17:09 PM] [Xiaomi Mi Robot Vaccum 1st Generation Neu] [Model=unknown] getSpeed | No vacuum cleaner is discovered yet.
[9/1/2024, 10:17:09 PM] [Xiaomi Mi Robot Vaccum 1st Generation Neu] [Model=unknown] INF ensureDevice | unknown model | The socket was destroyed or not initialised, initialising the device

But the connection failed.
I just checked all tickets but there is no solution that worked for me.

![20240901 Konsole Eingaben](https://github.com/user-attachments/assets/4d6c6d4b-ae5b-4c9f-ab93-3b764caa01c7)

Thanks for your support
Thomas

**Comment by panthertom** [comment]
I forgot: it’s a fritzbox mesh with an repeater (connected via lan)

**Comment by panthertom** [comment]
I checked die token.
HInt: 
At Github there ist an APP for MacOS and WIN named [Get_MiHome_devices_token](https://github.com/Maxmudjon/Get_MiHome_devices_token)
For me it worked perfectly.

**Comment by panthertom** [comment]
Done

**Comment by afharo** [comment]
> Done

From this comment, I get that you managed to make it work. I'll close the issue then... feel free to reopen it if it isn't true.
